(function(){'use strict';
const fallback=[
{id:'ai-automation',name:'AI Automation',category:'AI',icon:'⚙️',price:20000,description:'Automate repetitive business workflows, lead handling and internal processes.',features:['Workflow design','AI integration','Automation setup'],quote:true},
{id:'ai-assistant',name:'AI Assistant',category:'AI',icon:'✦',price:10000,description:'A practical AI assistant for FAQs, lead capture and customer support.',features:['Prompt design','Knowledge setup','Lead capture'],quote:true},
{id:'premium-website',name:'Premium Business Website',category:'Websites',icon:'◈',price:30000,description:'A fast, premium business website built around your goals and brand.',features:['Responsive UI','Deployment','Basic security'],quote:true},
{id:'security-review',name:'Website Security Review',category:'Cybersecurity',icon:'⌁',price:7500,description:'A structured review of common web security risks and hardening opportunities.',features:['Security review','Findings report','Hardening guidance'],quote:true},
{id:'automation-system',name:'Business Automation System',category:'Automation',icon:'↗',price:25000,description:'Connect forms, notifications, data and workflows into one operating system.',features:['Workflow mapping','Integrations','Testing'],quote:true}
];
let products=[...fallback],cart=JSON.parse(localStorage.getItem('oveshShopCart')||'[]'),category='All';
const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function save(){localStorage.setItem('oveshShopCart',JSON.stringify(cart));renderCart()}
async function load(){try{const s=await db.collection('shop_products').where('status','==','Published').get();if(!s.empty)products=s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){console.info('Shop catalog fallback active.');}renderCategories();renderProducts()}
function renderCategories(){const cats=['All',...new Set(products.map(p=>p.category).filter(Boolean))];$('categories').innerHTML=cats.map(c=>'<button class="'+(c===category?'active':'')+'" data-cat="'+esc(c)+'">'+esc(c)+'</button>').join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderCategories();renderProducts()})}
function renderProducts(){const q=$('search').value.toLowerCase();const list=products.filter(p=>(category==='All'||p.category===category)&&(!q||(p.name+' '+p.description+' '+p.category).toLowerCase().includes(q)));$('products').innerHTML=list.length?list.map(p=>'<article class="product"><div class="icon">'+esc(p.icon||'◈')+'</div><h3>'+esc(p.name)+'</h3><p>'+esc(p.description||'')+'</p><div class="chips">'+(p.features||[]).slice(0,4).map(x=>'<span class="chip">'+esc(x)+'</span>').join('')+'</div><div class="price">'+(p.price?'From '+money(p.price):'Request quote')+'</div><button class="primary" onclick="addToCart(\''+esc(p.id)+'\')">Add to Cart</button></article>').join(''):'<div class="product"><h3>No matching services</h3><p>Try another search or category.</p></div>'}
window.addToCart=id=>{const p=products.find(x=>x.id===id);if(!p)return;const found=cart.find(x=>x.id===id);if(found)found.qty++;else cart.push({id:p.id,name:p.name,price:Number(p.price||0),qty:1});save();openCart()};
function renderCart(){$('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);$('cartItems').innerHTML=cart.length?cart.map(x=>'<div class="cart-line"><div><strong>'+esc(x.name)+'</strong><button onclick="removeCart(\''+esc(x.id)+'\')">×</button></div><div class="qty"><span>'+money(x.price*x.qty)+'</span><span><button onclick="changeQty(\''+esc(x.id)+'\',-1)">−</button> '+x.qty+' <button onclick="changeQty(\''+esc(x.id)+'\',1)">+</button></span></div></div>').join(''):'<p class="muted">Your cart is empty.</p>';$('cartTotal').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0));$('checkoutBtn').disabled=!cart.length}
window.removeCart=id=>{cart=cart.filter(x=>x.id!==id);save()};window.changeQty=(id,n)=>{const x=cart.find(x=>x.id===id);if(!x)return;x.qty+=n;if(x.qty<1)cart=cart.filter(y=>y.id!==id);save()};
function openCart(){$('cartDrawer').classList.add('open');$('overlay').classList.add('open')};function closeCart(){$('cartDrawer').classList.remove('open');$('overlay').classList.remove('open')}
$('cartBtn').onclick=openCart;$('closeCart').onclick=closeCart;$('overlay').onclick=closeCart;$('search').oninput=renderProducts;
function waitForAuth(){return new Promise(resolve=>{if(auth.currentUser)return resolve(auth.currentUser);const unsub=auth.onAuthStateChanged(user=>{unsub();resolve(user||null);});});}\n$('checkoutBtn').onclick=async()=>{const user=await waitForAuth();if(!user){localStorage.setItem('oveshShopReturn','1');window.location.href='login.html?return=shop';return;}$('checkoutSummary').innerHTML=cart.map(x=>esc(x.name)+' × '+x.qty).join('<br>');$('checkoutStatus').textContent='';$('checkoutModal').classList.add('open')};document.querySelector('[data-close]').onclick=()=>$('checkoutModal').classList.remove('open');
$('checkoutForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),items=cart.map(x=>({productId:x.id,name:x.name,qty:x.qty,price:x.price})),orderId='SHOP-'+Date.now().toString().slice(-8);const payload={source:'shop',orderId,fullName:String(f.get('fullName')||'').trim(),email:String(f.get('email')||'').trim(),phone:String(f.get('phone')||'').trim(),selectedService:items.map(x=>x.name).join(', '),items,estimatedTotal:items.reduce((a,x)=>a+x.price*x.qty,0),uid:auth.currentUser.uid,userId:auth.currentUser.uid,projectDescription:String(f.get('message')||'').trim(),status:'Pending',paymentStatus:'Quote / payment pending',createdAt:firebase.firestore.FieldValue.serverTimestamp()};const s=$('checkoutStatus');s.textContent='Submitting…';try{await db.collection('service_requests').add(payload);
fetch('/api/send-shop-confirmation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId,fullName:payload.fullName,email:payload.email,items:payload.items,total:payload.estimatedTotal,requirements:payload.projectDescription})}).catch(err=>console.warn('Shop confirmation email failed:',err.message));
s.innerHTML='Request received. Your reference is <strong>'+esc(orderId)+'</strong>. A confirmation email has been sent to '+esc(payload.email)+'.';
cart=[];save();e.target.reset();}catch(err){console.error('Shop request submission failed:',err.code,err.message,err);const msg=err.code==='permission-denied'?'Your account is signed in, but this request is not permitted. Please contact the lab.':err.code==='unauthenticated'?'Your session expired. Please sign in again.':err.code==='unavailable'?'Service temporarily unavailable. Please try again.':'Could not submit right now. Please try again.';s.textContent=msg}};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
load();renderCart();
})();