(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let files=[],securityData={},college={subjects:[],practicals:[],projects:[],assignments:[],presentations:[],notes:[],skills:[],files:[],activity:[]};
let collegeSubjectId=null,collegeCategory=null;
const projects=[['Unitech Sealing','Website · Product Catalog · Client Delivery','IN PROGRESS'],['Ovesh Cyber Labs','Cybersecurity · Websites · Digital Assets','ACTIVE'],['Portfolio Project','Personal Brand · SEO · Web Development','REVIEW']];
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>{if(!n)return'0 B';let u=['B','KB','MB','GB','TB'],i=Math.min(4,Math.floor(Math.log(n)/Math.log(1024)));return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};
const now=()=>firebase.firestore.FieldValue.serverTimestamp();
const uid=()=>firebase.auth().currentUser?.uid||'unknown';
const cols={subjects:'college_subjects',practicals:'college_practicals',projects:'college_projects',assignments:'college_assignments',presentations:'college_presentations',notes:'college_notes',skills:'college_skills',files:'collegeFiles',activity:'college_activity'};
function dev(){let u=navigator.userAgent;return{device:/Mobi|Android|iPhone|iPad/i.test(u)?'Mobile / Tablet':'Desktop / Laptop',browser:/Edg\//i.test(u)?'Microsoft Edge':/Chrome\//i.test(u)?'Google Chrome':/Firefox\//i.test(u)?'Mozilla Firefox':/Safari\//i.test(u)?'Safari':'Browser',os:/Windows/i.test(u)?'Windows 10/11':/Android/i.test(u)?'Android':/Mac OS X/i.test(u)?'macOS':/Linux/i.test(u)?'Linux':'Not available',screen:`${screen.width} × ${screen.height}`}};
const setText=(id,value)=>{const e=$('#'+id);if(e)e.textContent=value};
function say(){try{if(!window.speechSynthesis)return;let u=new SpeechSynthesisUtterance('Ovesh Malpura, welcome to Ovesh Cloud. Your cloud is secure.');u.rate=.88;u.pitch=1.12;let go=()=>{let v=speechSynthesis.getVoices();u.voice=v.find(x=>/female|zira|samantha|aria|jenny/i.test(x.name))||v.find(x=>/^en/i.test(x.lang))||v[0];speechSynthesis.speak(u)};speechSynthesis.getVoices().length?go():speechSynthesis.onvoiceschanged=go}catch{}}
function detectLogin(){let d=dev();setText('loginDevice',d.device);setText('loginBrowser',d.browser);setText('loginOS',d.os);if(navigator.geolocation)navigator.geolocation.getCurrentPosition(()=>setText('loginLocation','Permission granted'),()=>setText('loginLocation','Permission unavailable'),{timeout:1500,maximumAge:300000})}
async function auth(user,pass){let controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{let r=await fetch('/api/oveshcloud-auth',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({username:user,password:pass}),signal:controller.signal}),x={};try{x=await r.json()}catch{}if(!r.ok)throw Error(x.error||`Authentication failed (${r.status})`);return x}catch(e){if(e.name==='AbortError')throw Error('Authentication timed out. Please try again.');if(e instanceof TypeError)throw Error('Unable to reach Ovesh Cloud authentication server. Please try again.');throw e}finally{clearTimeout(timer)}}
function showSecurity(data){securityData=data.security||{};let d=dev();$('#loginView')?.classList.add('hidden');$('#securityView')?.classList.remove('hidden');setText('secDevice',d.device);setText('secBrowser',d.browser);setText('secOS',d.os);setText('secScreen',d.screen);setText('secIP',securityData.ip||'Unavailable');setText('secTime',new Date(securityData.timestamp||Date.now()).toLocaleString('en-IN'));let p=$('#secPrecise');if(navigator.geolocation)navigator.geolocation.getCurrentPosition(x=>{if(p)p.textContent=`Permission granted · ${x.coords.latitude.toFixed(4)}, ${x.coords.longitude.toFixed(4)}`},()=>{if(p)p.textContent='Permission not granted'},{timeout:1500,maximumAge:300000});else if(p)p.textContent='Not supported';if(securityData.ip){fetch(`https://ipwho.is/${encodeURIComponent(securityData.ip)}`,{signal:AbortSignal.timeout(1400)}).then(r=>r.json()).then(x=>setText('secIPLocation',x.success===false?'Unavailable':[x.city,x.region,x.country].filter(Boolean).join(', ')||'Unavailable')).catch(()=>setText('secIPLocation','Unavailable'))}else setText('secIPLocation','Unavailable');say();let n=2;setText('countdown','Continuing in 2s');clearInterval(window.secTimer);window.secTimer=setInterval(()=>{n--;setText('countdown',n>0?`Continuing in ${n}s`:'Opening workspace…');if(n<=0){clearInterval(window.secTimer);openApp()}},1000)}
function welcome(){openApp()}
function openApp(){$('#securityView')?.classList.add('hidden');$('#appView')?.classList.remove('hidden');render('command');connectFirebase()}
async function connectFirebase(){try{if(!firebase.auth().currentUser)await firebase.auth().signInAnonymously();await loadFiles();await loadCollege()}catch(e){console.warn(e);showToast('Cloud connection is not ready. Check Firebase Authentication, Firestore and Storage rules.')}}
async function loadFiles(){try{let s=await firebase.firestore().collection('oveshCloudFiles').orderBy('createdAt','desc').limit(100).get();files=s.docs.map(d=>({id:d.id,...d.data()}))}catch{files=[]}}
async function loadCollege(){if(!firebase.auth().currentUser)return;let db=firebase.firestore();for(const k of Object.keys(cols)){try{let s=await db.collection(cols[k]).limit(300).get();college[k]=s.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn('College load',k,e);college[k]=[]}}render(currentPage==='college'?'college':'command')}
let currentPage='command',collegeTab='overview';
function render(p){currentPage=p;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));let names={command:'Command Center',projects:'Client Projects',storage:'Cloud Storage',activity:'Activity',college:'College',security:'Security'};$('#pageTitle').textContent=names[p]||'College';let h=p==='command'?command():p==='projects'?projectPage():p==='storage'?storage():p==='activity'?activity():p==='college'?collegePage():secPage();$('#page').innerHTML=h;bind()}
function command(){let used=files.reduce((a,f)=>a+Number(f.size||0),0);return`<div class="hero-command"><div class="hero-card"><div class="hero-tag">PRIVATE DIGITAL COMMAND CENTER</div><h1>Everything important.<br><span>One secure cloud.</span></h1><p>Projects, client work, files, college assets and delivery operations — organized inside your private Ovesh Cloud workspace.</p><div class="hero-core"><strong>OC</strong></div></div><div class="metric-stack"><div class="metric"><small>CLIENT PROJECTS</small><strong>03</strong><p>Private workspaces</p></div><div class="metric"><small>CLOUD ASSETS</small><strong>${files.length}</strong><p>Files indexed</p></div><div class="metric"><small>WORKSPACE HEALTH</small><strong class="green">100%</strong><p>Core services operational</p></div></div></div><div class="section-title"><h3>Client Projects</h3><span>PRIVATE WORKSPACES</span></div><div class="projects">${projects.map(p=>card(p)).join('')}</div><div class="dashboard-grid"><div class="storage-card"><div class="card-head"><h4>Cloud Storage</h4><span>LIVE INDEX</span></div><div class="storage-number">${bytes(used)}</div><div class="storage-meta">indexed file data · Firebase Storage</div><div class="bar"><i style="width:${Math.min(100,Math.max(2,used/10737418240*100))}%"></i></div><button class="file-action" data-page="storage">Open storage →</button></div><div class="pipeline"><div class="card-head"><h4>Delivery Pipeline</h4><span>PROJECT OPERATIONS</span></div><div class="pipeline-line"><div class="stage active"><i></i>PLANNING</div><div class="stage active"><i></i>DEVELOPMENT</div><div class="stage active"><i></i>REVIEW</div><div class="stage"><i></i>DELIVERY</div></div></div></div><div class="dashboard-grid"><div class="activity-card"><div class="card-head"><h4>Recent Activity</h4><span>LIVE</span></div>${rows()}</div><div class="health-card"><div class="card-head"><h4>All Systems Operational</h4><span class="green">● HEALTHY</span></div><div class="health-list"><div>Authentication <span>Operational</span></div><div>Cloud Database <span>Operational</span></div><div>File Storage <span>${firebase.auth().currentUser?'Connected':'Checking'}</span></div><div>Private Session <span>Secure</span></div></div></div></div>`}
function card(p){return`<article class="project-card"><div class="project-top"><span class="hero-tag">CLIENT WORKSPACE</span><span class="status">${p[2]}</span></div><h4>${esc(p[0])}</h4><p>${esc(p[1])}</p><div class="project-foot">Private workspace · Open →</div></article>`}
function rows(){return[['Workspace accessed','Ovesh Cloud command center'],['Security session created','Private authentication verified'],['Storage index refreshed',`${files.length} files indexed`],['Workspace ready','Ovesh-WORKPLACE online']].map(x=>`<div class="activity-row"><i class="activity-dot"></i><div><b>${x[0]}</b><small>${x[1]}</small></div></div>`).join('')}
function projectPage(){return`<div class="section-title"><h3>Client Projects</h3><span>03 WORKSPACES</span></div><div class="projects">${projects.map(card).join('')}</div>`}
function storage(){let used=files.reduce((a,f)=>a+Number(f.size||0),0);return`<div class="section-title"><h3>Cloud Storage</h3><span>REAL FIREBASE STORAGE</span></div><div class="dashboard-grid"><div class="storage-card"><div class="card-head"><h4>Storage usage</h4><span>INDEXED</span></div><div class="storage-number">${bytes(used)}</div><div class="storage-meta">${files.length} indexed files</div><div class="bar"><i style="width:${Math.min(100,Math.max(2,used/10737418240*100))}%"></i></div><p class="muted">Usage is calculated from files indexed by Ovesh Cloud.</p></div><div class="storage-card"><div class="card-head"><h4>Upload assets</h4><span>FIREBASE STORAGE</span></div><p class="muted">Upload files directly into your private cloud.</p><input id="fileInput" type="file" multiple><button id="uploadBtn" class="primary-btn">UPLOAD TO OVESH CLOUD <span>↑</span></button><div id="uploadStatus" class="muted"></div></div></div><div class="section-title"><h3>Files & Assets</h3><span>INDEXED MATERIALS</span></div><div class="file-table"><div class="file-row head"><span>FILE</span><span>SIZE</span><span>DATE</span><span>ACTION</span></div>${files.length?files.map(f=>`<div class="file-row"><span class="file-name">${esc(f.name)}<span class="file-sub">${esc(f.contentType||'file')}</span></span><span>${bytes(f.size)}</span><span>${f.createdAt?.toDate?f.createdAt.toDate().toLocaleDateString('en-IN'):'—'}</span><button class="file-action" data-download="${esc(f.url)}">Download</button></div>`).join(''):`<div class="empty">No files yet.<br>Upload your first project asset above.</div>`}</div>`}
function activity(){return`<div class="section-title"><h3>Recent Activity</h3><span>PRIVATE EVENT STREAM</span></div><div class="activity-card">${rows()}${college.activity.length?college.activity.slice(-10).reverse().map(a=>`<div class="activity-row"><i class="activity-dot"></i><div><b>${esc(a.action||'College activity')}</b><small>${esc(a.detail||'Academic workspace update')}</small></div></div>`).join(''):''}</div>`}
function collegeCounts(){let pendingP=college.practicals.filter(x=>['NOT STARTED','IN PROGRESS'].includes(String(x.status||'').toUpperCase())).length;let activeProj=college.projects.filter(x=>['IDEA','PLANNING','IN PROGRESS','REVIEW'].includes(String(x.status||'').toUpperCase())).length;let pendingA=college.assignments.filter(x=>['PENDING','IN PROGRESS'].includes(String(x.status||'').toUpperCase())).length;return{pendingP,activeProj,pendingA}}
function collegePage(){return`<div class="college-shell"><div class="college-hero"><div><div class="hero-tag">PRIVATE ACADEMIC OPERATING SYSTEM</div><h1>College Workspace</h1><p>Your academic workspace is organized by subject. Open a subject to access its own assignments, practicals, files, notes, projects and presentations.</p></div></div><div class="college-section-head"><div><h2>Subjects</h2><p>Select a subject to enter its dedicated academic workspace.</p></div><div class="college-tools"><button class="primary-btn small" data-action="add-subject">+ ADD SUBJECT</button></div></div><div class="college-cards">${college.subjects.length?college.subjects.map(s=>{let ps=college.practicals.filter(x=>x.subjectId===s.id).length,as=college.assignments.filter(x=>x.subjectId===s.id).length,pr=college.projects.filter(x=>x.subjectId===s.id).length,pe=college.presentations.filter(x=>x.subjectId===s.id).length,no=college.notes.filter(x=>x.subjectId===s.id).length,ff=college.files.filter(x=>x.subjectId===s.id).length;return`<article class="college-card subject-card"><div class="card-head"><span class="hero-tag">SUBJECT</span><button class="icon-btn" data-edit-subject="${s.id}">Edit</button></div><h3>${esc(s.name)}</h3><p>${esc(s.description||'Academic subject workspace')}</p><div class="mini-stats"><span>Practicals <b>${ps}</b></span><span>Assignments <b>${as}</b></span><span>Files <b>${ff}</b></span><span>Notes <b>${no}</b></span><span>Projects <b>${pr}</b></span><span>Presentations <b>${pe}</b></span></div><div class="card-actions"><button data-open-subject="${s.id}">OPEN SUBJECT →</button><button class="danger-link" data-delete-subject="${s.id}">Delete</button></div></article>`}).join(''):empty('NO SUBJECTS YET','Add PPC, WP, BLA, LS or another subject when you are ready. Nothing is auto-created.')}</div></div>`}
function stat(label,value,sub){return`<div class="college-stat"><small>${label}</small><strong>${value}</strong><span>${sub||''}</span></div>`}
function subjectName(id){return college.subjects.find(x=>x.id===id)?.name||'Unassigned subject'}
function workRow(title,status,meta,date){return`<div class="college-row"><div><b>${esc(title)}</b><small>${esc(meta||'')}</small></div><span class="college-status">${esc(status||'—')}</span>${date?`<small>${esc(date)}</small>`:''}</div>`}
function empty(title,desc){return`<div class="college-empty"><strong>${esc(title)}</strong><span>${esc(desc)}</span></div>`}
function categoryCard(id,key,title,icon,desc){let n=college[key].filter(x=>x.subjectId===id).length;return`<article class="college-card category-card"><div class="category-icon">${icon}</div><h3>${title}</h3><p>${desc}</p><div class="category-meta"><strong>${n}</strong><span>${n===1?'item':'items'}</span></div><div class="card-actions"><button data-subject-category="${id}" data-category="${key}">OPEN ${title.toUpperCase()} →</button><button class="icon-btn" data-subject-add="${id}" data-add-type="${key}">+ ADD</button></div></article>`}
function subjectWorkspace(id){let s=college.subjects.find(x=>x.id===id);if(!s)return;collegeSubjectId=id;collegeCategory=null;$('#page').innerHTML=`<div class="college-shell"><div class="college-hero"><div><div class="hero-tag">SUBJECT WORKSPACE</div><h1>${esc(s.name)}</h1><p>${esc(s.description||'Academic subject workspace')}</p></div><button class="primary-btn" data-college-back>← COLLEGE</button></div><div class="college-section-head"><div><h2>${esc(s.name)} · Academic Sections</h2><p>Everything for this subject stays inside its own category.</p></div></div><div class="college-cards">${categoryCard(id,'assignments','Assignments','📘','Tasks, questions and submissions.')} ${categoryCard(id,'practicals','Practicals','🧪','Practical records and experiments.')} ${categoryCard(id,'files','Files','📁','Subject-specific cloud files and resources.')} ${categoryCard(id,'notes','Notes','📝','Notes, study material and references.')} ${categoryCard(id,'projects','Projects','🚀','Projects belonging to this subject.')} ${categoryCard(id,'presentations','Presentations','🎤','PPT, PDF and presentation work.')}</div></div>`;bind()}
function subjectCategoryPage(id,key){let s=college.subjects.find(x=>x.id===id);if(!s||!college[key])return;collegeSubjectId=id;collegeCategory=key;let meta={assignments:['Assignments','Tasks, questions and submissions.','assignment'],practicals:['Practicals','Practical records and experiments.','practical'],files:['Files','Subject-specific cloud files and resources.','file'],notes:['Notes','Notes, study material and references.','note'],projects:['Projects','Projects belonging to this subject.','project'],presentations:['Presentations','PPT, PDF and presentation work.','presentation']}[key];let arr=college[key].filter(x=>x.subjectId===id);let title=meta[0],type=meta[2];$('#page').innerHTML=`<div class="college-shell"><div class="college-hero"><div><div class="hero-tag">${esc(s.name)} · ${title.toUpperCase()}</div><h1>${title}</h1><p>${meta[1]}</p></div><button class="primary-btn" data-open-subject="${id}">← ${esc(s.name)}</button></div><div class="college-section-head"><div><h2>${esc(s.name)} / ${title}</h2><p>${arr.length} ${arr.length===1?'item':'items'} in this category.</p></div><button class="primary-btn small" data-subject-add="${id}" data-add-type="${key}">+ ADD ${title.toUpperCase().replace(/S$/,'')}</button></div>${arr.length?`<div class="college-list">${arr.map(x=>`<article class="college-list-card"><div><span class="hero-tag">${title.toUpperCase()}</span><h3>${esc(x.title||x.name||x.filename||x.name||'Untitled')}</h3><p>${esc(x.description||x.task||x.content?.slice(0,180)||x.fileName||x.name||'')}</p></div><span class="college-status">${esc(x.status||'READY')}</span><div class="list-actions">${key==='practicals'?`<button data-open-practical="${x.id}">OPEN</button>`:''}<button data-edit-${type}="${x.id}">EDIT</button><button data-delete-${type}="${x.id}" class="danger-link">DELETE</button></div></article>`).join('')}</div>`:empty(`NO ${title.toUpperCase()} YET`,`Add the first item to ${title.toLowerCase()} for ${s.name}.`)}</div>`;bind()}
function practicalsPage(){return listPage('Practicals','Practical records organized by subject.','practical','college.practicals',x=>`${x.number?`Practical ${esc(x.number)} · `:''}${esc(x.title)}`,x=>subjectName(x.subjectId),['NOT STARTED','IN PROGRESS','COMPLETED','SUBMITTED'])}
function collegeProjectsPage(){return listPage('College Projects','Separate from client and personal projects.','project','college.projects',x=>esc(x.name),x=>subjectName(x.subjectId),['IDEA','PLANNING','IN PROGRESS','REVIEW','COMPLETED','SUBMITTED'])}
function presentationsPage(){return listPage('College Presentations','PPT/PPTX, PDF and supporting presentation assets.','presentation','college.presentations',x=>esc(x.title),x=>subjectName(x.subjectId),['PENDING','IN PROGRESS','COMPLETED','SUBMITTED'])}
function assignmentsPage(){return listPage('Assignments','Track work and deadlines by subject.','assignment','college.assignments',x=>esc(x.title),x=>subjectName(x.subjectId),['PENDING','IN PROGRESS','COMPLETED','SUBMITTED'])}
function listPage(title,desc,type,key,titleFn,metaFn,statuses){let arr=college[type==='practical'?'practicals':type==='project'?'projects':type==='presentation'?'presentations':'assignments'];let label=type[0].toUpperCase()+type.slice(1);return`<div class="college-section-head"><div><h2>${title}</h2><p>${desc}</p></div><div class="college-tools"><input id="collegeSearch" placeholder="Search ${title.toLowerCase()}…"><select id="statusFilter"><option value="">All statuses</option>${statuses.map(s=>`<option>${s}</option>`).join('')}</select><button class="primary-btn small" data-action="add-${type}">+ ADD ${label.toUpperCase()}</button></div></div><div class="college-list" data-list-type="${type}">${arr.length?arr.slice().sort((a,b)=>String(b.updatedAt?.seconds||0).localeCompare(String(a.updatedAt?.seconds||0))).map(x=>`<article class="college-list-card" data-searchable="${esc(titleFn(x)+' '+metaFn(x))}" data-status="${esc(x.status||'')}"><div><span class="hero-tag">${label.toUpperCase()}</span><h3>${titleFn(x)}</h3><p>${esc(metaFn(x))}</p></div><span class="college-status">${esc(x.status||'NOT STARTED')}</span><div class="list-actions"><button data-edit-${type}="${x.id}">EDIT</button><button data-delete-${type}="${x.id}" class="danger-link">DELETE</button></div></article>`).join(''):empty(`NO ${title.toUpperCase()} YET`,`Create your first ${type} to start organizing academic work.`)}</div>`}
function notesPage(){return`<div class="college-section-head"><div><h2>Notes & Resources</h2><p>Organized academic notes and reference material.</p></div><button class="primary-btn small" data-action="add-note">+ ADD NOTE</button></div><div class="college-cards">${college.notes.length?college.notes.map(n=>`<article class="college-card"><span class="hero-tag">NOTE · ${esc(subjectName(n.subjectId))}</span><h3>${esc(n.title)}</h3><p>${esc((n.content||'').slice(0,180))}</p><div class="card-actions"><button data-edit-note="${n.id}">EDIT</button><button data-delete-note="${n.id}" class="danger-link">DELETE</button></div></article>`).join(''):empty('NO NOTES YET','Create your first academic note.')}</div>`}
function skillsPage(){let cats={};college.skills.forEach(s=>(cats[s.category||'General']??=[]).push(s));return`<div class="college-section-head"><div><h2>Skills</h2><p>Skills learned through academic subjects. No invented proficiency scores.</p></div><button class="primary-btn small" data-action="add-skill">+ ADD SKILL</button></div>${Object.keys(cats).length?Object.entries(cats).map(([cat,arr])=>`<section class="skill-group"><div class="card-head"><h3>${esc(cat)}</h3><span>${arr.length} SKILLS</span></div><div class="skill-grid">${arr.map(s=>`<article class="skill-card"><b>${esc(s.name)}</b><span>${esc(s.status||'LEARNING')}</span><small>${esc(subjectName(s.subjectId))}</small><div><button data-edit-skill="${s.id}">Edit</button><button data-delete-skill="${s.id}" class="danger-link">Delete</button></div></article>`).join('')}</div></section>`).join(''):empty('NO SKILLS YET','Add skills as they are learned through college work.')}`}
function formModal(title,fields,submitLabel='SAVE'){let id='collegeModal';return`<div class="college-modal-backdrop" id="${id}"><div class="college-modal"><div class="modal-head"><strong>${esc(title)}</strong><button data-close-modal>×</button></div><form id="collegeForm"><div class="college-form-grid">${fields.map(f=>f.html).join('')}</div><div class="modal-actions"><button type="button" data-close-modal class="file-action">CANCEL</button><button class="primary-btn" type="submit">${submitLabel} <span>→</span></button></div></form></div></div>`}
function field(name,label,value='',type='text',required=false,extra=''){return{html:`<label class="college-field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${extra}></label>`}}
function selectField(name,label,options,value='',required=false){return{html:`<label class="college-field">${label}<select name="${name}" ${required?'required':''}><option value="">Select…</option>${options.map(o=>`<option value="${esc(o.value??o)}" ${String(o.value??o)===String(value)?'selected':''}>${esc(o.label??o)}</option>`).join('')}</select></label>`}}
function textareaField(name,label,value='',required=false){return{html:`<label class="college-field full">${label}<textarea name="${name}" rows="6" ${required?'required':''}>${esc(value)}</textarea></label>`}}
function showModal(html,onSubmit){document.body.insertAdjacentHTML('beforeend',html);let m=$('#collegeModal');$('#collegeForm').onsubmit=async e=>{e.preventDefault();let b=e.submitter;b.disabled=true;try{await onSubmit(new FormData(e.target));m.remove()}catch(err){console.error(err);showToast(err.message||'Unable to save.');b.disabled=false}};$$('[data-close-modal]').forEach(x=>x.onclick=()=>m.remove())}
async function logCollege(action,detail){try{await firebase.firestore().collection(cols.activity).add({action,detail,userId:uid(),createdAt:now()});college.activity.unshift({action,detail})}catch(e){console.warn('activity',e)}}
async function saveDoc(type,id,data,action){let ref=firebase.firestore().collection(cols[type]);if(id)await ref.doc(id).set({...data,updatedAt:now(),userId:uid()},{merge:true});else await ref.add({...data,createdAt:now(),updatedAt:now(),userId:uid()});await logCollege(action,data.title||data.name||'Academic record');await loadCollege()}
function subjectModal(id){let s=id&&college.subjects.find(x=>x.id===id);showModal(formModal(id?'Edit Subject':'Add Subject',[field('name','SUBJECT NAME',s?.name||'', 'text',true),field('description','SHORT DESCRIPTION',s?.description||'')]),async fd=>{await saveDoc('subjects',id,{name:fd.get('name').trim(),description:fd.get('description').trim()},id?'Subject updated':'Subject created');showToast(id?'Subject updated.':'Subject created.')})}
function practicalModal(id){let x=id&&college.practicals.find(v=>v.id===id);showModal(formModal(id?'Edit Practical':'Add Practical',[selectField('subjectId','SUBJECT',college.subjects.map(s=>({value:s.id,label:s.name})),x?.subjectId||collegeSubjectId,true),field('number','PRACTICAL NUMBER',x?.number||''),field('title','TITLE',x?.title||'', 'text',true),textareaField('task','QUESTION / TASK',x?.task||''),textareaField('description','DESCRIPTION',x?.description||''),field('date','DATE',x?.date||'', 'date'),selectField('status','STATUS',['NOT STARTED','IN PROGRESS','COMPLETED','SUBMITTED'],x?.status||'NOT STARTED',true)]),async fd=>{await saveDoc('practicals',id,{subjectId:fd.get('subjectId'),number:fd.get('number'),title:fd.get('title').trim(),task:fd.get('task').trim(),description:fd.get('description').trim(),date:fd.get('date'),status:fd.get('status')},id?'Practical updated':'Practical created');showToast('Practical saved.')})}
function projectModal(id){let x=id&&college.projects.find(v=>v.id===id);showModal(formModal(id?'Edit College Project':'Add College Project',[selectField('subjectId','SUBJECT',college.subjects.map(s=>({value:s.id,label:s.name})),x?.subjectId||collegeSubjectId,true),field('name','PROJECT NAME',x?.name||'', 'text',true),textareaField('description','DESCRIPTION',x?.description||''),selectField('status','STATUS',['IDEA','PLANNING','IN PROGRESS','REVIEW','COMPLETED','SUBMITTED'],x?.status||'IDEA',true),field('startDate','START DATE',x?.startDate||'','date'),field('deadline','DEADLINE',x?.deadline||'','date')]),async fd=>{await saveDoc('projects',id,{subjectId:fd.get('subjectId'),name:fd.get('name').trim(),description:fd.get('description').trim(),status:fd.get('status'),startDate:fd.get('startDate'),deadline:fd.get('deadline')},id?'College project updated':'College project created');showToast('Project saved.')})}
function assignmentModal(id){let x=id&&college.assignments.find(v=>v.id===id);showModal(formModal(id?'Edit Assignment':'Add Assignment',[selectField('subjectId','SUBJECT',college.subjects.map(s=>({value:s.id,label:s.name})),x?.subjectId||collegeSubjectId,true),field('title','ASSIGNMENT TITLE',x?.title||'','text',true),textareaField('description','DESCRIPTION',x?.description||''),field('dueDate','DUE DATE',x?.dueDate||'','date'),selectField('status','STATUS',['PENDING','IN PROGRESS','COMPLETED','SUBMITTED'],x?.status||'PENDING',true)]),async fd=>{await saveDoc('assignments',id,{subjectId:fd.get('subjectId'),title:fd.get('title').trim(),description:fd.get('description').trim(),dueDate:fd.get('dueDate'),status:fd.get('status')},id?'Assignment updated':'Assignment created');showToast('Assignment saved.')})}
function presentationModal(id){let x=id&&college.presentations.find(v=>v.id===id);showModal(formModal(id?'Edit Presentation':'Add Presentation',[selectField('subjectId','SUBJECT',college.subjects.map(s=>({value:s.id,label:s.name})),x?.subjectId||collegeSubjectId,true),field('title','TITLE',x?.title||'','text',true),field('projectId','PROJECT ID (OPTIONAL)',x?.projectId||''),textareaField('description','DESCRIPTION',x?.description||''),selectField('status','SUBMISSION STATUS',['PENDING','IN PROGRESS','COMPLETED','SUBMITTED'],x?.status||'PENDING')]),async fd=>{await saveDoc('presentations',id,{subjectId:fd.get('subjectId'),title:fd.get('title').trim(),projectId:fd.get('projectId').trim(),description:fd.get('description').trim(),status:fd.get('status')},id?'Presentation updated':'Presentation created');showToast('Presentation saved.')})}
function noteModal(id){let x=id&&college.notes.find(v=>v.id===id);showModal(formModal(id?'Edit Note':'Add Note',[selectField('subjectId','SUBJECT',college.subjects.map(s=>({value:s.id,label:s.name})),x?.subjectId||collegeSubjectId,false),field('title','TITLE',x?.title||'','text',true),textareaField('content','CONTENT',x?.content||'',true),field('tags','TAGS (comma separated)',x?.tags||'')]),async fd=>{await saveDoc('notes',id,{subjectId:fd.get('subjectId'),title:fd.get('title').trim(),content:fd.get('content').trim(),tags:fd.get('tags').trim()},id?'Note updated':'Note created');showToast('Note saved.')})}
function skillModal(id){let x=id&&college.skills.find(v=>v.id===id);showModal(formModal(id?'Edit Skill':'Add Skill',[field('name','SKILL NAME',x?.name||'','text',true),field('category','CATEGORY',x?.category||'General','text',true),selectField('subjectId','SUBJECT',college.subjects.map(s=>({value:s.id,label:s.name})),x?.subjectId||collegeSubjectId||''),selectField('status','STATUS',['LEARNING','PRACTICING','FAMILIAR','COMPLETED'],x?.status||'LEARNING',true)]),async fd=>{await saveDoc('skills',id,{name:fd.get('name').trim(),category:fd.get('category').trim(),subjectId:fd.get('subjectId'),status:fd.get('status')},id?'Skill updated':'Skill added');showToast('Skill saved.')})}
async function removeItem(type,id,label){if(!confirm(`Delete ${label}?\n\nThis removes the real academic record. Associated files are not silently deleted.`))return;await firebase.firestore().collection(cols[type]).doc(id).delete();await logCollege(`${label} deleted`,label);await loadCollege();showToast(`${label} deleted.`)}
async function deleteSubject(id){let children=['practicals','projects','assignments','presentations','notes','skills'].some(k=>college[k].some(x=>x.subjectId===id));if(children&&!confirm('This subject has connected academic records. Delete the subject record only? Related records will remain so no data is silently destroyed.'))return;await removeItem('subjects',id,'Subject')}
function practicalDetail(id){let x=college.practicals.find(v=>v.id===id);if(!x)return;let s=subjectName(x.subjectId);$('#page').innerHTML=`<div class="college-shell"><div class="college-hero"><div><div class="hero-tag">${esc(s)} · PRACTICAL</div><h1>${esc(x.title)}</h1><p>Practical ${esc(x.number||'')} · ${esc(x.status||'NOT STARTED')}</p></div><button class="primary-btn" data-subject-category="${x.subjectId}" data-category="practicals">← PRACTICALS</button></div><div class="college-panel"><div class="card-head"><h3>Question / Task</h3><span>${esc(x.date||'')}</span></div><p class="muted">${esc(x.task||'No task description added.')}</p></div><div class="college-panel"><div class="card-head"><h3>Description</h3></div><p class="muted">${esc(x.description||'No description added.')}</p></div></div>`;bind()}
function bind(){
$$('[data-page]').forEach(b=>b.onclick=()=>render(b.dataset.page));
$$('[data-download]').forEach(b=>b.onclick=()=>location.href=b.dataset.download);
let up=$('#uploadBtn');if(up)up.onclick=upload;
$$('[data-college-tab]').forEach(b=>b.onclick=()=>{collegeTab=b.dataset.collegeTab;render('college')});
$$('[data-action]').forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==='add-subject')subjectModal();if(a==='add-practical')practicalModal();if(a==='add-project')projectModal();if(a==='add-assignment')assignmentModal();if(a==='add-presentation')presentationModal();if(a==='add-note')noteModal();if(a==='add-skill')skillModal()});
$$('[data-edit-subject]').forEach(b=>b.onclick=()=>subjectModal(b.dataset.editSubject));$$('[data-delete-subject]').forEach(b=>b.onclick=()=>deleteSubject(b.dataset.deleteSubject));
$$('[data-open-subject]').forEach(b=>b.onclick=()=>subjectWorkspace(b.dataset.openSubject));$$('[data-college-back]').forEach(b=>b.onclick=()=>render('college'));
$$('[data-subject-category]').forEach(b=>b.onclick=()=>b.dataset.category==='practicals'&&b.dataset.openPractical?practicalDetail(b.dataset.openPractical):subjectCategoryPage(b.dataset.subjectCategory,b.dataset.category));
$$('[data-open-practical]').forEach(b=>b.onclick=()=>practicalDetail(b.dataset.openPractical));
$$('[data-subject-add]').forEach(b=>b.onclick=()=>{collegeSubjectId=b.dataset.subjectAdd;let t=b.dataset.addType;if(t==='assignments')assignmentModal();if(t==='practicals')practicalModal();if(t==='projects')projectModal();if(t==='presentations')presentationModal();if(t==='notes')noteModal();if(t==='files')showToast('File upload is available from Cloud Storage; subject file indexing will be added without changing global storage.');});
$$('[data-edit-practical]').forEach(b=>b.onclick=()=>practicalModal(b.dataset.editPractical));$$('[data-delete-practical]').forEach(b=>b.onclick=()=>removeItem('practicals',b.dataset.deletePractical,'Practical'));
$$('[data-edit-project]').forEach(b=>b.onclick=()=>projectModal(b.dataset.editProject));$$('[data-delete-project]').forEach(b=>b.onclick=()=>removeItem('projects',b.dataset.deleteProject,'College project'));
$$('[data-edit-assignment]').forEach(b=>b.onclick=()=>assignmentModal(b.dataset.editAssignment));$$('[data-delete-assignment]').forEach(b=>b.onclick=()=>removeItem('assignments',b.dataset.deleteAssignment,'Assignment'));
$$('[data-edit-presentation]').forEach(b=>b.onclick=()=>presentationModal(b.dataset.editPresentation));$$('[data-delete-presentation]').forEach(b=>b.onclick=()=>removeItem('presentations',b.dataset.editPresentation,'Presentation'));
$$('[data-edit-note]').forEach(b=>b.onclick=()=>noteModal(b.dataset.editNote));$$('[data-delete-note]').forEach(b=>b.onclick=()=>removeItem('notes',b.dataset.deleteNote,'Note'));
$$('[data-edit-skill]').forEach(b=>b.onclick=()=>skillModal(b.dataset.editSkill));$$('[data-delete-skill]').forEach(b=>b.onclick=()=>removeItem('skills',b.dataset.deleteSkill,'Skill'));
let q=$('#collegeSearch');if(q)q.oninput=()=>filterCollege(q.value);let sf=$('#statusFilter');if(sf)sf.onchange=()=>filterCollege(q?.value||'');
}
function filterCollege(q){let s=(q||'').toLowerCase(),st=($('#statusFilter')?.value||'').toLowerCase();$$('[data-searchable]').forEach(x=>{let ok=x.dataset.searchable.toLowerCase().includes(s)&&(!st||x.dataset.status.toLowerCase()===st);x.style.display=ok?'':'none'})}
async function upload(){let input=$('#fileInput'),status=$('#uploadStatus');if(!input.files.length)return showToast('Choose files first.');try{for(let i=0;i<input.files.length;i++){let f=input.files[i],path=`ovesh-cloud/${uid()}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,ref=firebase.storage().ref(path),task=ref.put(f,{contentType:f.type||'application/octet-stream'});await new Promise((res,rej)=>task.on('state_changed',s=>status.textContent=`Uploading ${i+1}/${input.files.length} · ${Math.round(s.bytesTransferred/s.totalBytes*100)}%`,rej,res));let url=await ref.getDownloadURL();await firebase.firestore().collection('oveshCloudFiles').add({name:f.name,size:f.size,contentType:f.type||'application/octet-stream',storagePath:path,url,uploadedBy:uid(),createdAt:now()})}await loadFiles();showToast('Upload complete.');render('storage')}catch(e){console.error(e);status.textContent=e.code||e.message;showToast('Upload failed — check Firebase Storage rules.')}}
function showToast(t){let x=$('#toast');x.textContent=t;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),2800)}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();let b=$('#loginBtn'),err=$('#loginError');b.disabled=true;err.textContent='';try{let x=await auth($('#username').value.trim(),$('#password').value);showSecurity(x);setText('loginIP',x.security?.ip||'Unavailable')}catch(x){err.textContent=x.message;b.disabled=false}});
$('#continueBtn')?.addEventListener('click',openApp);
$('#logoutBtn')?.addEventListener('click',()=>{sessionStorage.clear();location.reload()});
detectLogin();
})();