const state={view:'home',files:[],used:0,quota:5*1024*1024*1024,workspace:null,favorites:new Set(),query:''};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>{n=Number(n||0);if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(2)} GB`};
const pct=()=>Math.min(100,(state.used/state.quota)*100);
function toast(message,error=false){const t=$('toast');t.textContent=message;t.classList.toggle('error',error);t.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add('hidden'),2800)}
function modal(title,body){$('modal').innerHTML=`<div class="modal-card"><div class="panel-head"><h2>${esc(title)}</h2><button class="btn" onclick="closeModal()">Close</button></div>${body}</div>`;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function go(view){state.view=view;state.query='';if($('globalSearch'))$('globalSearch').value='';render()}
function fileIcon(f){const t=(f.type||'').toLowerCase();if(t.includes('image'))return'▧';if(t.includes('pdf'))return'▤';if(t.includes('video'))return'▶';if(t.includes('audio'))return'♪';if(t.includes('zip')||t.includes('compressed'))return'◈';if(t.includes('text')||t.includes('json'))return'≡';return'□'}
function saveFavorites(){localStorage.setItem('oveshcloud_favorites',JSON.stringify([...state.favorites]))}
function loadFavorites(){try{state.favorites=new Set(JSON.parse(localStorage.getItem('oveshcloud_favorites')||'[]'))}catch{state.favorites=new Set()}}
async function api(action,opts={}){const q=new URLSearchParams({action,workspace:state.workspace,...(opts.query||{})});const r=await fetch(`../api/oveshcloud-r2?${q}`,{method:opts.method||'GET',headers:opts.body?{'Content-Type':'application/json'}:undefined,body:opts.body?JSON.stringify({...opts.body,workspace:state.workspace}):undefined});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function load(){try{const d=await api('list');state.files=(d.items||[]).map(x=>({key:x.key,name:x.name||x.key.split('/').pop().replace(/^\d+-[a-z0-9]+-/i,''),size:Number(x.size||0),updatedAt:x.updatedAt,type:x.type||'application/octet-stream'}));state.used=Number(d.used||0);state.quota=Number(d.quota||state.quota);updateStorage();render()}catch(e){updateStorage();renderError(e.message)}}
function updateStorage(){$('sideUsage').textContent=`${fmt(state.used)} of ${fmt(state.quota)}`;$('sideBar').style.width=`${pct()}%`;$('sidePercent').textContent=`${Math.round(pct())}%`}
function header(title,desc,actions=''){return`<div class="hero"><div><div class="eyebrow">OVESH CLOUD</div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`}
function filtered(files){const q=state.query.toLowerCase().trim();return q?files.filter(f=>`${f.name} ${f.type}`.toLowerCase().includes(q)):files}
function sorted(){return [...state.files].sort((a,b)=>new Date(b.updatedAt||0)-new Date(a.updatedAt||0))}
function empty(title='No files yet.',icon='□'){return`<div class="empty"><div class="empty-icon">${icon}</div><strong>${esc(title)}</strong><p>Upload something to see it here.</p></div>`}
function render(){const v=state.view;$('crumb').textContent=v==='home'?'Home':v[0].toUpperCase()+v.slice(1);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const files=filtered(sorted());
 if(v==='home'){$('content').innerHTML=header('Your cloud, beautifully simple.','A calm, private workspace for the files that matter.',`<button class="btn primary" onclick="openPicker()">＋ Upload files</button>`)+`<div class="grid stats"><div class="card stat"><div class="stat-label">Storage used</div><div class="stat-value">${fmt(state.used)}</div><div class="stat-sub">of ${fmt(state.quota)} available</div></div><div class="card stat"><div class="stat-label">Files</div><div class="stat-value">${state.files.length}</div><div class="stat-sub">Stored in your cloud</div></div><div class="card stat"><div class="stat-label">Free space</div><div class="stat-value">${fmt(Math.max(0,state.quota-state.used))}</div><div class="stat-sub">Ready for uploads</div></div><div class="card stat"><div class="stat-label">Workspace</div><div class="stat-value">Private</div><div class="stat-sub">No account required</div></div></div><div class="grid section-grid"><section class="card panel"><div class="panel-head"><h2>Quick actions</h2></div><div class="grid quick-grid"><div class="card quick" onclick="openPicker()"><div class="quick-icon">↑</div><div><h3>Upload files</h3><p>Documents, photos, videos and more.</p></div><span class="quick-count">Add to your cloud →</span></div><div class="card quick" onclick="go('files')"><div class="quick-icon">▱</div><div><h3>Browse My Files</h3><p>View, download and manage everything.</p></div><span class="quick-count">${state.files.length} file${state.files.length===1?'':'s'} →</span></div></div></section><section class="card panel"><div class="panel-head"><h2>Recent</h2><button class="btn" onclick="go('recent')">See all</button></div>${activity(files.slice(0,5))}</section></div>`}
 else if(v==='files'){$('content').innerHTML=header('My Files','Everything stored in your Ovesh Cloud workspace.',`<button class="btn" onclick="createFolder()">＋ New folder</button><button class="btn primary" onclick="openPicker()">↑ Upload</button>`)+`<div class="card table-card table-wrap">${fileTable(files)}</div>`}
 else if(v==='recent'){$('content').innerHTML=header('Recent','Your latest uploads and changes.')+`<div class="card table-card table-wrap">${fileTable(files.slice(0,30))}</div>`}
 else if(v==='favorites'){const fav=files.filter(f=>state.favorites.has(f.key));$('content').innerHTML=header('Favorites','Files you marked for quick access.')+`<div class="card table-card table-wrap">${fileTable(fav)}</div>`}
 else {$('content').innerHTML=header('Trash','Deleted files are removed from cloud storage immediately.')+empty('Trash is empty.','⌫')}}
function activity(items){return items.length?`<div class="activity">${items.map(f=>`<div class="activity-row"><div class="activity-icon">${fileIcon(f)}</div><div class="activity-copy"><b>${esc(f.name)}</b><small>${fmt(f.size)} · ${date(f.updatedAt)}</small></div><button class="mini-btn" onclick="downloadFile('${encodeURIComponent(f.key)}')">Open</button></div>`).join('')}</div>`:empty('Nothing here yet.','◷')}
function date(value){return value?new Date(value).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'Just now'}
function fileTable(items){if(!items.length)return empty(state.query?`No files match “${state.query}”.`:'No files in this view.','▱');return`<table class="table"><thead><tr><th>Name</th><th>Type</th><th>Size</th><th>Modified</th><th></th></tr></thead><tbody>${items.map(f=>`<tr><td><div class="file-cell"><div class="file-icon">${fileIcon(f)}</div><span class="file-name" title="${esc(f.name)}">${esc(f.name)}</span></div></td><td class="muted">${esc(prettyType(f.type))}</td><td class="muted">${fmt(f.size)}</td><td class="muted">${date(f.updatedAt)}</td><td><div class="row-actions"><button class="mini-btn" onclick="toggleFavorite('${encodeURIComponent(f.key)}')">${state.favorites.has(f.key)?'★':'☆'}</button><button class="mini-btn" onclick="downloadFile('${encodeURIComponent(f.key)}')">Open</button><button class="mini-btn" onclick="renameFile('${encodeURIComponent(f.key)}')">Rename</button><button class="mini-btn danger" onclick="deleteFile('${encodeURIComponent(f.key)}')">Delete</button></div></td></tr>`).join('')}</tbody></table>`}
function prettyType(type){if(!type)return'File';if(type.includes('/'))return type.split('/')[1].toUpperCase().slice(0,12);return type}
function openPicker(){ $('fileInput').value='';$('fileInput').click() }
async function uploadFiles(files){if(!files.length)return;for(const f of files){try{if(f.size>100*1024*1024)throw new Error(`${f.name} is larger than the 100 MB upload limit.`);toast(`Preparing ${f.name}…`);const p=await api('presign-upload',{query:{name:f.name,size:f.size,type:f.type||'application/octet-stream'}});await putWithProgress(p.url,f);toast(`${f.name} uploaded`)}catch(e){toast(e.message,true);break}}await load()}
function putWithProgress(url,file){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',url);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)toast(`Uploading ${file.name} · ${Math.round(e.loaded/e.total*100)}%`)};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error(`Upload failed for ${file.name}`));xhr.onerror=()=>reject(new Error(`Upload failed for ${file.name}`));xhr.send(file)})}
async function downloadFile(encoded){try{const key=decodeURIComponent(encoded);const d=await api('presign-download',{query:{key}});const a=document.createElement('a');a.href=d.url;a.target='_blank';a.rel='noopener';a.click()}catch(e){toast(e.message,true)}}
async function deleteFile(encoded){const key=decodeURIComponent(encoded);const f=state.files.find(x=>x.key===key);if(!f)return;modal('Delete file',`<p>“${esc(f.name)}” will be permanently removed from your Ovesh Cloud storage.</p><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="confirmDelete('${encodeURIComponent(key)}')">Delete</button></div>`)}
async function confirmDelete(encoded){closeModal();try{await api('delete',{method:'POST',body:{key:decodeURIComponent(encoded)}});state.favorites.delete(decodeURIComponent(encoded));saveFavorites();toast('File deleted');await load()}catch(e){toast(e.message,true)}}
function toggleFavorite(encoded){const key=decodeURIComponent(encoded);state.favorites.has(key)?state.favorites.delete(key):state.favorites.add(key);saveFavorites();render()}
function renameFile(encoded){const key=decodeURIComponent(encoded);const f=state.files.find(x=>x.key===key);if(!f)return;modal('Rename file',`<form class="form" onsubmit="event.preventDefault();submitRename('${encodeURIComponent(key)}')"><label>New name<input id="renameInput" value="${esc(f.name)}" maxlength="180" autofocus></label><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save name</button></div></form>`);setTimeout(()=>{$('renameInput')?.focus();$('renameInput')?.select()},40)}
async function submitRename(encoded){const key=decodeURIComponent(encoded),name=$('renameInput').value.trim();if(!name)return;try{await api('rename',{method:'POST',body:{key,name}});closeModal();toast('File renamed');await load()}catch(e){toast(e.message,true)}}
async function createFolder(){modal('Create folder',`<form class="form" onsubmit="event.preventDefault();submitFolder()"><label>Folder name<input id="folderInput" maxlength="80" placeholder="e.g. Projects" autofocus></label><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Create folder</button></div></form>`)}
async function submitFolder(){const name=$('folderInput').value.trim();if(!name)return;try{await api('create-folder',{method:'POST',body:{name}});closeModal();toast('Folder created');await load()}catch(e){toast(e.message,true)}}
function renderError(message){$('content').innerHTML=header('Finish your cloud setup','Ovesh Cloud is ready, but the R2 storage environment still needs to be connected.')+`<div class="card panel"><div class="eyebrow">CLOUDFLARE R2</div><h2>Storage connection required</h2><p class="muted">${esc(message)}</p><p>Add <b>R2_ACCOUNT_ID</b>, <b>R2_ACCESS_KEY_ID</b>, <b>R2_SECRET_ACCESS_KEY</b> and <b>R2_BUCKET</b> to your Vercel environment, then refresh.</p></div>`}
function setupDragDrop(){let depth=0;window.addEventListener('dragenter',e=>{e.preventDefault();depth++;$('dropzone').classList.remove('hidden')});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('dragleave',e=>{e.preventDefault();depth--;if(depth<=0){depth=0;$('dropzone').classList.add('hidden')}});window.addEventListener('drop',e=>{e.preventDefault();depth=0;$('dropzone').classList.add('hidden');uploadFiles([...e.dataTransfer.files])})}
$('nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)go(b.dataset.view)});$('fileInput').addEventListener('change',()=>uploadFiles([...$('fileInput').files]));$('newButton').addEventListener('click',openPicker);$('refreshButton').addEventListener('click',()=>{toast('Refreshing…');load()});$('globalSearch').addEventListener('input',e=>{state.query=e.target.value;render()});$('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
(function init(){let ws=localStorage.getItem('oveshcloud_workspace');if(!ws){ws=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;localStorage.setItem('oveshcloud_workspace',ws)}state.workspace=ws;loadFavorites();setupDragDrop();load()})();
