const state={view:'home',files:[],trash:[],used:0,quota:5*1024*1024*1024,workspace:null};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>{n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'};
const pct=()=>Math.min(100,(state.used/state.quota)*100);
function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');clearTimeout(window.__t);window.__t=setTimeout(()=>$('toast').classList.add('hidden'),2800)}
function modal(title,body){$('modal').innerHTML=`<div class="modal-card"><div class="panel-head"><h2>${title}</h2><button class="btn" onclick="closeModal()">Close</button></div>${body}</div>`;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function go(v){state.view=v;render()}
function fileIcon(f){const t=(f.type||'').toLowerCase();if(t.includes('image'))return'▧';if(t.includes('pdf'))return'▤';if(t.includes('video'))return'▶';if(t.includes('audio'))return'♪';if(t.includes('zip')||t.includes('compressed'))return'◈';return'□'}
async function api(action,opts={}){const q=new URLSearchParams({action,workspace:state.workspace,...(opts.query||{})});const r=await fetch(`../api/oveshcloud-r2?${q}`,{method:opts.method||'GET',headers:opts.body?{'Content-Type':'application/json'}:undefined,body:opts.body?JSON.stringify({...opts.body,workspace:state.workspace}):undefined});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function load(){try{const d=await api('list');state.files=d.items.map(x=>({key:x.key,name:x.key.split('/').pop().replace(/^\d+-[a-z0-9]+-/i,''),size:x.size,updatedAt:x.updatedAt,type:'file'}));state.used=d.used||0;state.quota=d.quota||state.quota;updateStorage();render()}catch(e){toast(e.message);renderError(e.message)}}
function updateStorage(){$('sideUsage').textContent=`${fmt(state.used)} of ${fmt(state.quota)}`;$('sideBar').style.width=`${pct()}%`}
function header(title,desc,actions=''){return`<div class="hero"><div><div class="eyebrow">OVESH CLOUD</div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`}
function render(){const v=state.view;$('crumb').textContent=v==='home'?'Overview':v[0].toUpperCase()+v.slice(1);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const files=[...state.files].sort((a,b)=>new Date(b.updatedAt||0)-new Date(a.updatedAt||0));if(v==='home'){$('content').innerHTML=header('Your cloud, beautifully simple.','A private browser workspace powered by Ovesh Cloud and Cloudflare R2.',`<button class="btn primary" onclick="uploadFile()">＋ Upload files</button>`)+`<div class="grid stats"><div class="card"><div class="stat-label">Storage used</div><div class="stat-value">${fmt(state.used)}</div><div class="stat-sub">of ${fmt(state.quota)} available</div></div><div class="card"><div class="stat-label">Files</div><div class="stat-value">${state.files.length}</div><div class="stat-sub">Stored in your cloud</div></div><div class="card"><div class="stat-label">Free space</div><div class="stat-value">${fmt(Math.max(0,state.quota-state.used))}</div><div class="stat-sub">Ready for uploads</div></div><div class="card"><div class="stat-label">Workspace</div><div class="stat-value">Local</div><div class="stat-sub">No account required</div></div></div><div class="grid section-grid"><div class="card"><div class="panel-head"><h2>Quick actions</h2></div><div class="grid workspace"><div class="card tile" onclick="uploadFile()"><div><div class="eyebrow">UPLOAD</div><h3>Add files</h3><p>Upload documents, photos, videos and more.</p></div><div class="count">＋</div></div><div class="card tile" onclick="go('files')"><div><div class="eyebrow">BROWSE</div><h3>My Files</h3><p>View, download and manage everything.</p></div><div class="count">${state.files.length}</div></div></div></div><div class="card"><div class="panel-head"><h2>Recent files</h2><button class="btn" onclick="go('recent')">View all</button></div>${fileRows(files.slice(0,6))}</div></div>`}else if(v==='files'){$('content').innerHTML=header('My Files','Everything stored in your Ovesh Cloud workspace.',`<button class="btn primary" onclick="uploadFile()">＋ Upload files</button>`)+`<div class="card table-wrap">${fileTable(files)}</div>`}else if(v==='recent'){$('content').innerHTML=header('Recent','Your latest uploads and changes.','')+`<div class="card table-wrap">${fileTable(files.slice(0,25))}</div>`}else{$('content').innerHTML=header('Trash','Deleted files will be removed from storage immediately.','')+`<div class="empty">Trash is currently empty.</div>`}}
function fileRows(items){return items.length?`<div class="activity">${items.map(f=>`<div class="activity-row"><div class="activity-icon">${fileIcon(f)}</div><div style="flex:1"><b>${esc(f.name)}</b><small>${fmt(f.size)} · ${f.updatedAt?new Date(f.updatedAt).toLocaleString('en-IN'):'Just now'}</small></div><button class="btn" onclick="downloadFile('${encodeURIComponent(f.key)}')">Download</button></div>`).join('')}</div>`:'<div class="empty">No files yet. Upload your first file.</div>'}
function fileTable(items){return items.length?`<table class="table"><tr><th>Name</th><th>Type</th><th>Size</th><th>Modified</th><th></th></tr>${items.map(f=>`<tr><td><b>${fileIcon(f)} &nbsp;${esc(f.name)}</b></td><td>${esc(f.type||'File')}</td><td>${fmt(f.size)}</td><td>${f.updatedAt?new Date(f.updatedAt).toLocaleString('en-IN'):'—'}</td><td><div class="actions"><button class="btn" onclick="downloadFile('${encodeURIComponent(f.key)}')">Open</button><button class="btn danger" onclick="deleteFile('${encodeURIComponent(f.key)}')">Delete</button></div></td></tr>`).join('')}</table>`:'<div class="empty">No files in this view.</div>'}
async function uploadFile(){const i=document.createElement('input');i.type='file';i.multiple=true;i.onchange=async()=>{const files=[...i.files];if(!files.length)return;for(const f of files){try{toast(`Preparing ${f.name}…`);const p=await api('presign-upload',{query:{name:f.name,size:f.size,type:f.type||'application/octet-stream'}});toast(`Uploading ${f.name}…`);const r=await fetch(p.url,{method:'PUT',headers:{'Content-Type':f.type||'application/octet-stream'},body:f});if(!r.ok)throw new Error(`Upload failed for ${f.name}`)}catch(e){toast(e.message);break}}await load();toast('Upload complete')};i.click()}
async function downloadFile(encoded){try{const key=decodeURIComponent(encoded);const d=await api('presign-download',{query:{key}});window.open(d.url,'_blank','noopener,noreferrer')}catch(e){toast(e.message)}}
async function deleteFile(encoded){const key=decodeURIComponent(encoded);const f=state.files.find(x=>x.key===key);if(!f||!confirm(`Delete “${f.name}”?`))return;try{await api('delete',{method:'POST',body:{key}});toast('File deleted');await load()}catch(e){toast(e.message)}}
function renderError(message){$('content').innerHTML=header('Storage setup required','Ovesh Cloud is connected to the R2 API, but the storage environment is not configured yet.')+`<div class="card"><h2>Cloudflare R2</h2><p class="muted">${esc(message)}</p><p>Add the R2 environment variables in your Vercel project, then refresh this page.</p></div>`}
$('nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)go(b.dataset.view)});
$('globalSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();if(!q){render();return}const matches=state.files.filter(f=>`${f.name} ${f.type}`.toLowerCase().includes(q));$('content').innerHTML=header('Search','Matching files in your workspace.',`<button class="btn" onclick="go('files')">Back to files</button>`)+`<div class="card table-wrap">${fileTable(matches)}</div>`});
(function init(){let ws=localStorage.getItem('oveshcloud_workspace');if(!ws){ws=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}-${Math.random().toString(16).slice(2)}`;localStorage.setItem('oveshcloud_workspace',ws)}state.workspace=ws;load()})();
