(()=>{'use strict';
const db=()=>firebase.firestore();
const auth=()=>firebase.auth();
const uid=()=>auth().currentUser?.uid||'';
const COL='college_subjects';
const DEFAULT_SUBJECTS=[
 {name:'PPC',description:'Academic workspace for PPC.'},
 {name:'Web Programming',description:'HTML, CSS, JavaScript and web development coursework.'},
 {name:'LS',description:'Academic workspace for LS.'}
];
let subjects=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{if(typeof window.showToast==='function')window.showToast(m);else{const t=document.getElementById('toast');if(t){t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2500)}}};
async function seed(){const u=uid();if(!u)return;const snap=await db().collection(COL).where('userId','==',u).get();const names=new Set(snap.docs.map(d=>String(d.data().name||'').trim().toLowerCase()));const batch=db().batch();let n=0;for(const s of DEFAULT_SUBJECTS){if(!names.has(s.name.toLowerCase())){const ref=db().collection(COL).doc();batch.set(ref,{userId:u,name:s.name,description:s.description,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),isDefault:true});n++}}if(n)await batch.commit();}
async function load(){const u=uid();if(!u){renderMessage('Sign in required','Please sign in to open your College workspace.');return}try{await seed();const snap=await db().collection(COL).where('userId','==',u).get();subjects=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.name).localeCompare(String(b.name)));render();}catch(e){console.error('College load failed',e);renderMessage('College data could not be loaded','The College database could not be read. Check Firebase Firestore permissions and try again.');}}
function renderMessage(title,text){const p=document.getElementById('page');if(p)p.innerHTML=`<div class="college-fix"><div class="cf-panel"><div class="cf-kicker">OVESH CLOUD™ · COLLEGE</div><h1>${esc(title)}</h1><p>${esc(text)}</p><button class="cf-primary" data-cf-retry>RETRY</button></div></div>`;}
function render(){const p=document.getElementById('page');if(!p)return;p.innerHTML=`<div class="college-fix"><header class="cf-head"><div><div class="cf-kicker">PRIVATE ACADEMIC OPERATING SYSTEM</div><h1>College</h1><p>Subjects, practicals, projects and academic files in one workspace.</p></div><button class="cf-primary" data-cf-add>+ ADD SUBJECT</button></header><div class="cf-stats"><div><small>SUBJECTS</small><b>${subjects.length}</b></div><div><small>DEFAULT SUBJECTS</small><b>${subjects.filter(s=>s.isDefault).length}</b></div><div><small>STATUS</small><b>ONLINE</b></div></div><section class="cf-panel"><div class="cf-panelhead"><div><h2>Your Subjects</h2><span>REAL FIRESTORE DATA</span></div></div><div class="cf-grid">${subjects.map(s=>`<article class="cf-card"><div class="cf-icon">${esc(s.name.slice(0,2).toUpperCase())}</div><div class="cf-cardbody"><small>SUBJECT</small><h3>${esc(s.name)}</h3><p>${esc(s.description||'Academic subject workspace')}</p><div class="cf-actions"><button data-cf-open="${s.id}">OPEN WORKSPACE →</button><button data-cf-edit="${s.id}">EDIT</button><button class="danger" data-cf-delete="${s.id}">DELETE</button></div></div></article>`).join('')||'<div class="cf-empty">No subjects found.</div>'}</div></section></div>`;}
function modal(title,fields,onSave){const m=document.createElement('div');m.className='cf-modal';m.innerHTML=`<div class="cf-dialog"><div class="cf-dialoghead"><div><small>COLLEGE WORKSPACE</small><h2>${esc(title)}</h2></div><button data-cf-close>×</button></div><div class="cf-form">${fields.map(f=>`<label>${esc(f.label)}${f.type==='textarea'?`<textarea name="${f.name}" ${f.required?'required':''}>${esc(f.value||'')}</textarea>`:`<input name="${f.name}" type="${f.type||'text'}" value="${esc(f.value||'')}" ${f.required?'required':''}>`}</label>`).join('')}</div><div class="cf-dialogactions"><button data-cf-close>CANCEL</button><button class="cf-primary" data-cf-save>SAVE</button></div></div>`;document.body.appendChild(m);m.querySelectorAll('[data-cf-close]').forEach(b=>b.onclick=()=>m.remove());m.querySelector('[data-cf-save]').onclick=async()=>{const data={};fields.forEach(f=>data[f.name]=m.querySelector(`[name="${f.name}"]`).value.trim());if(fields.some(f=>f.required&&!data[f.name])){toast('Please complete the required fields.');return}try{await onSave(data);m.remove();await load();}catch(e){console.error(e);toast(e.message||'Unable to save changes.')}};}
function add(){modal('Add Subject',[{name:'name',label:'Subject name',required:true},{name:'description',label:'Description',type:'textarea'}],async d=>{await db().collection(COL).add({userId:uid(),name:d.name,description:d.description,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),isDefault:false});toast('Subject created successfully.');});}
function edit(id){const s=subjects.find(x=>x.id===id);if(!s)return;modal('Edit Subject',[{name:'name',label:'Subject name',value:s.name,required:true},{name:'description',label:'Description',type:'textarea',value:s.description||''}],async d=>{await db().collection(COL).doc(id).update({name:d.name,description:d.description,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});toast('Subject updated successfully.');});}
async function del(id){const s=subjects.find(x=>x.id===id);if(!s)return;if(!confirm(`Delete ${s.name}? This removes the subject record only; review related academic records before deleting them.`))return;try{await db().collection(COL).doc(id).delete();toast('Subject deleted.');await load();}catch(e){console.error(e);toast(e.message||'Unable to delete subject.')}}
function open(id){const s=subjects.find(x=>x.id===id);if(!s)return;const p=document.getElementById('page');p.innerHTML=`<div class="college-fix"><header class="cf-head"><div><button class="cf-back" data-cf-back>← COLLEGE</button><div class="cf-kicker">SUBJECT WORKSPACE</div><h1>${esc(s.name)}</h1><p>${esc(s.description||'Academic subject workspace')}</p></div><button class="cf-primary" data-cf-edit="${s.id}">EDIT SUBJECT</button></header><div class="cf-modulegrid">${['Practicals','Assignments','Projects','Presentations','Notes','Resources','Skills','Files'].map(x=>`<button class="cf-module"><b>${x}</b><span>Open ${x.toLowerCase()} →</span></button>`).join('')}</div><div class="cf-panel"><div class="cf-empty"><strong>Subject workspace ready</strong><span>Your ${esc(s.name)} records can be connected here without mixing them with other subjects.</span></div></div></div>`;}
document.addEventListener('click',e=>{const a=e.target.closest('[data-page="college"]');if(a){e.preventDefault();e.stopImmediatePropagation();setTimeout(load,0);}},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-cf-add]');if(b){e.preventDefault();add();return}const r=e.target.closest('[data-cf-retry]');if(r){load();return}const back=e.target.closest('[data-cf-back]');if(back){load();return}const op=e.target.closest('[data-cf-open]');if(op){open(op.dataset.cfOpen);return}const ed=e.target.closest('[data-cf-edit]');if(ed){edit(ed.dataset.cfEdit);return}const de=e.target.closest('[data-cf-delete]');if(de){del(de.dataset.cfDelete);return}},true);
auth().onAuthStateChanged(u=>{if(u&&document.getElementById('page')&&document.querySelector('[data-page="college"].active'))load();});
window.OveshCollegeFix={load};
})();
