(function(){'use strict';var s=document.createElement('link');s.rel='stylesheet';s.href='/oveshcloud/ultra-cloud.css?v=20260826-ultra1';document.head.appendChild(s);function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(n){n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'}
function decorate(){if(!window.state||!document.getElementById('content'))return;document.body.dataset.ocView=state.view||'home';if(state.view!=='home')return;const c=document.getElementById('content');const used=(state.files||[]).reduce((a,x)=>a+Number(x.size||0),0);const projects=(state.projects||[]).slice(0,4);const activity=(state.activity||[]).slice().sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,5);c.innerHTML=`<div class="elite-home">
<section class="elite-command"><div class="elite-command-copy"><div class="elite-eyebrow">OVESH CLOUD™ / PRIVATE OPERATING SYSTEM</div><h1>Your entire digital world.<br><span style="background:linear-gradient(90deg,#fff,#8eefff,#a990ff);-webkit-background-clip:text;color:transparent">Beautifully organized.</span></h1><p>A premium private workspace for client delivery, college work, web projects, files and everything you build.</p><div class="elite-actions"><button class="elite-btn primary" onclick="newProject()">＋ New client project</button><button class="elite-btn" onclick="uploadFile()">↑ Upload to Cloud</button></div></div><div class="elite-orb" aria-hidden="true"></div></section>
<section class="elite-metrics"><div class="elite-metric featured"><div class="label">Cloud storage</div><div class="num">${fmt(used)}</div><div class="hint">Private workspace · encrypted access</div><div class="elite-storage"><div class="elite-storage-head"><span>OVESH CLOUD™</span><b>ACTIVE</b></div><div class="elite-bar"><span></span></div></div></div><div class="elite-metric"><div class="label">Client projects</div><div class="num">${state.projects.length}</div><div class="hint">Active & archived work</div></div><div class="elite-metric"><div class="label">Cloud files</div><div class="num">${state.files.length}</div><div class="hint">Documents & media</div></div><div class="elite-metric"><div class="label">Clients</div><div class="num">${state.clients.length}</div><div class="hint">Delivery relationships</div></div></section>
<section class="elite-main-grid"><div class="elite-panel"><div class="elite-panel-head"><div><h2>Client Projects</h2><span>Your highest-priority workspace</span></div><button class="elite-btn" onclick="go('projects')">View all →</button></div><div class="elite-projects">${projects.length?projects.map((x,i)=>`<div class="elite-project" onclick="newProject('${x.id}')"><div class="project-icon">${String(i+1).padStart(2,'0')}</div><h3>${esc(x.name||'Untitled project')}</h3><p>${esc(x.description||x.category||'Client workspace')}</p><span class="status">${esc(x.status||'ACTIVE')}</span><span class="count">↗</span></div>`).join(''):`<div class="empty" style="grid-column:1/-1">No client projects yet.<br><button class="elite-btn primary" style="margin-top:14px" onclick="newProject()">Create your first project</button></div>`}</div></div>
<div class="elite-panel"><div class="elite-panel-head"><div><h2>Live activity</h2><span>Latest workspace events</span></div><button class="elite-btn" onclick="go('activity')">All →</button></div><div class="elite-list">${activity.length?activity.map(x=>`<div class="elite-row"><span class="dot"></span><div><b>${esc(x.label)}</b><small>OVESH CLOUD™ activity</small></div></div>`).join(''):`<div class="empty">No recent activity.</div>`}</div></div></section>
<section class="elite-panel"><div class="elite-panel-head"><div><h2>College workspace</h2><span>Keep practicals, assignments and academic work structured</span></div><button class="elite-btn" onclick="go('projects')">Open College →</button></div><div class="elite-quick"><button onclick="go('projects')"><span>◈</span><strong>Practicals</strong><small>Projects & assignments</small></button><button onclick="go('web')"><span>◇</span><strong>Web Programming</strong><small>Web projects & demos</small></button><button onclick="go('files')"><span>▱</span><strong>Documents</strong><small>PDFs & presentations</small></button><button onclick="go('catalogs')"><span>◫</span><strong>Client Catalogs</strong><small>Controlled delivery</small></button></div></section>
<div class="elite-footer-mark">OVESH CLOUD™ · PRIVATE WORKSPACE · OVESH MALPURA CYBER LABS</div></div>`}
function hook(){if(typeof window.render!=='function')return setTimeout(hook,80);const r=window.render;if(r.__elite)return;function wrapped(){r.apply(this,arguments);requestAnimationFrame(decorate)}wrapped.__elite=true;window.render=wrapped;requestAnimationFrame(decorate)}
hook();window.addEventListener('load',()=>setTimeout(decorate,100));
})();