(()=>{'use strict';
const B2_API='/api/backblaze';let context={type:null,id:null};
const user=()=>firebase.auth().currentUser;
async function api(body){const u=user();if(!u)throw new Error('Secure cloud session is not ready.');const token=await u.getIdToken();const r=await fetch(B2_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body),cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'Backblaze storage request failed.');return x}
function xhrPut(url,file,onProgress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',url);x.setRequestHeader('Content-Type',file.type||'application/octet-stream');x.upload.onprogress=e=>{if(e.lengthComputable&&onProgress)onProgress(Math.round(e.loaded/e.total*100))};x.onload=()=>x.status>=200&&x.status<300?resolve():reject(new Error(`Upload failed (${x.status})`));x.onerror=()=>reject(new Error('Upload network error.'));x.onabort=()=>reject(new Error('Upload cancelled.'));x.send(file)})}
async function upload(file,folder,onProgress){if(!file)throw new Error('Select a file first.');const p=await api({action:'presign-upload',fileName:file.name,contentType:file.type||'application/octet-stream',size:file.size,folder});await xhrPut(p.uploadUrl,file,onProgress);return p}
async function downloadRemote(objectKey){if(!objectKey)throw new Error('File location is missing.');const p=await api({action:'presign-download',objectKey});window.location.assign(p.downloadUrl);return p}
async function deleteRemote(objectKey){return api({action:'delete',objectKey})}
async function saveFile(collection,data){return firebase.firestore().collection(collection).add({...data,createdAt:firebase.firestore.FieldValue.serverTimestamp()})}
function refresh(){window.location.reload()}
function setContext(e){const b=e.target.closest('[data-v2-view]');if(!b)return;const v=String(b.dataset.v2View||'').split(':');context={type:v[0]||null,id:v[1]||null}}
async function storageUpload(e){const b=e.target.closest('#uploadBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const input=document.getElementById('fileInput'),status=document.getElementById('uploadStatus'),list=[...(input?.files||[])];if(!list.length){if(status)status.textContent='Select at least one file.';return}b.disabled=true;try{for(const f of list){if(status)status.textContent=`Uploading ${f.name} · 0%`;const r=await upload(f,'ovesh-cloud',p=>{if(status)status.textContent=`Uploading ${f.name} · ${p}%`});await saveFile('oveshCloudFiles',{userId:user().uid,name:f.name,size:f.size,contentType:f.type||'file',url:r.objectKey,storageProvider:'backblaze-b2',objectKey:r.objectKey});}if(status)status.textContent='Upload complete · Backblaze B2';setTimeout(refresh,350)}catch(err){console.error(err);if(status)status.textContent=err.message||'Upload failed.'}finally{b.disabled=false}}
async function collegeUpload(e){const b=e.target.closest('#cv3Upload');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const modal=b.closest('.cv3-modal'),input=modal?.querySelector('#cv3File'),status=modal?.querySelector('#cv3Status'),f=input?.files?.[0];if(!f){if(status)status.textContent='Select a file first.';return}const cat=modal.querySelector('#cv3Cat')?.value||'general';b.disabled=true;try{const type=context.type||'record',id=context.id||'unknown';let subjectId=null;try{const s=await firebase.firestore().collection(type==='practical'?'college_practicals':type==='project'?'college_projects':type==='assignment'?'college_assignments':type==='presentation'?'college_presentations':type==='note'?'college_notes':type==='skill'?'college_skills':'college_practicals').doc(id).get();subjectId=s.exists?s.data().subjectId||null:null}catch{}if(status)status.textContent='Preparing secure upload…';const r=await upload(f,`college/${subjectId||'general'}/${type}/${id}`,p=>{if(status)status.textContent=`Uploading ${p}%`});await saveFile('collegeFiles',{userId:user().uid,workspace:'college',subjectId,entityId:id,entityType:type,category:cat,name:f.name,size:f.size,contentType:f.type||'file',url:r.objectKey,storageProvider:'backblaze-b2',objectKey:r.objectKey});await saveFile('college_activity',{userId:user().uid,action:'File uploaded',detail:f.name,entityId:id,entityType:type});if(status)status.textContent='Upload complete · Backblaze B2';input.value='';setTimeout(refresh,350)}catch(err){console.error(err);if(status)status.textContent=err.message||'Upload failed.'}finally{b.disabled=false}}
async function collegeDelete(e){const b=e.target.closest('[data-del-file]');if(!b)return;const id=b.dataset.delFile;if(!id)return;try{const snap=await firebase.firestore().collection('collegeFiles').doc(id).get();const f=snap.data();if(!f)return;if(f.storageProvider==='imagekit'&&f.imagekitFileId){e.preventDefault();e.stopImmediatePropagation();if(!confirm('Delete this file from the previous storage and College storage?'))return;const u=user();const token=await u.getIdToken();const r=await fetch('/api/imagekit',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'delete',fileId:f.imagekitFileId})});if(!r.ok)throw new Error('Unable to delete previous storage file.')}else if(f.storageProvider==='backblaze-b2'&&f.objectKey){e.preventDefault();e.stopImmediatePropagation();if(!confirm('Delete this file from Backblaze B2 and College storage?'))return;await deleteRemote(f.objectKey)}else return;await firebase.firestore().collection('collegeFiles').doc(id).delete();await firebase.firestore().collection('college_activity').add({userId:user().uid,action:'File deleted',detail:f.name||id,entityId:f.entityId||null,entityType:f.entityType||null,createdAt:firebase.firestore.FieldValue.serverTimestamp()});b.closest('.cv3-file')?.remove()}catch(err){console.error(err);alert(err.message||'Unable to delete file.')}}
async function handleDownload(e){const b=e.target.closest('[data-download]');if(!b)return;const value=b.dataset.download;if(!value)return;e.preventDefault();e.stopImmediatePropagation();try{if(value.startsWith('users/'))await downloadRemote(value);else if(/^https?:\/\//i.test(value))window.location.assign(value)}catch(err){console.error(err);alert(err.message||'Unable to download file.')}}
document.addEventListener('click',e=>{setContext(e);storageUpload(e);collegeUpload(e);collegeDelete(e);handleDownload(e)},true);
window.OVESH_STORAGE={upload,downloadRemote,deleteRemote};
})();
