(()=>{'use strict';
const IK_API='/api/imagekit';
let context={type:null,id:null};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const user=()=>firebase.auth().currentUser;
async function auth(){const u=user();if(!u)throw new Error('Secure cloud session is not ready.');const token=await u.getIdToken();const r=await fetch(IK_API,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'ImageKit authentication failed.');return x}
async function upload(file,folder,onProgress){if(!file)throw new Error('Select a file first.');const a=await auth();const fd=new FormData();fd.append('file',file);fd.append('fileName',file.name.replace(/[^a-zA-Z0-9._-]/g,'_'));fd.append('publicKey',a.publicKey);fd.append('signature',a.signature);fd.append('expire',String(a.expire));fd.append('token',a.token);fd.append('useUniqueFileName','true');fd.append('folder',folder);const xhr=new XMLHttpRequest();const result=await new Promise((resolve,reject)=>{xhr.open('POST','https://upload.imagekit.io/api/v1/files/upload');xhr.upload.onprogress=e=>{if(e.lengthComputable&&onProgress)onProgress(Math.round(e.loaded/e.total*100))};xhr.onload=()=>{let x={};try{x=JSON.parse(xhr.responseText||'{}')}catch{}if(xhr.status>=200&&xhr.status<300)resolve(x);else reject(new Error(x.message||x.error||`ImageKit upload failed (${xhr.status})`))};xhr.onerror=()=>reject(new Error('Upload network error.'));xhr.onabort=()=>reject(new Error('Upload cancelled.'));xhr.send(fd)});return result}
async function deleteRemote(fileId){const u=user();if(!u||!fileId)throw new Error('Secure cloud session is not ready.');const token=await u.getIdToken();const r=await fetch(IK_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'delete',fileId})});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'Unable to delete ImageKit file.');return x}
async function saveFile(collection,data){return firebase.firestore().collection(collection).add({...data,createdAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function refresh(){try{if(typeof window.loadFiles==='function')await window.loadFiles()}catch{}window.location.reload()}
function setContext(e){const b=e.target.closest('[data-v2-view]');if(!b)return;const v=String(b.dataset.v2View||'').split(':');context={type:v[0]||null,id:v[1]||null}}
async function storageUpload(e){const b=e.target.closest('#uploadBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const input=document.getElementById('fileInput'),status=document.getElementById('uploadStatus'),list=[...(input?.files||[])];if(!list.length){if(status)status.textContent='Select at least one file.';return}b.disabled=true;try{for(const f of list){if(status)status.textContent=`Uploading ${f.name} · 0%`;const r=await upload(f,`ovesh-cloud/${user().uid}`,p=>{if(status)status.textContent=`Uploading ${f.name} · ${p}%`});await saveFile('oveshCloudFiles',{userId:user().uid,name:f.name,size:f.size,contentType:f.type||'file',url:r.url,storageProvider:'imagekit',imagekitFileId:r.fileId,imagekitPath:r.filePath,imagekitVersionId:r.versionInfo?.id||null});}if(status)status.textContent='Upload complete.';setTimeout(refresh,250)}catch(err){console.error(err);if(status)status.textContent=err.message||'Upload failed.'}finally{b.disabled=false}}
async function collegeUpload(e){const b=e.target.closest('#cv3Upload');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const modal=b.closest('.cv3-modal'),input=modal?.querySelector('#cv3File'),status=modal?.querySelector('#cv3Status'),f=input?.files?.[0];if(!f){if(status)status.textContent='Select a file first.';return}const cat=modal.querySelector('#cv3Cat')?.value||'general';b.disabled=true;try{const type=context.type||'record',id=context.id||'unknown';let subjectId=null;try{const s=await firebase.firestore().collection(type==='practical'?'college_practicals':type==='project'?'college_projects':type==='assignment'?'college_assignments':type==='presentation'?'college_presentations':type==='note'?'college_notes':type==='skill'?'college_skills':'college_practicals').doc(id).get();subjectId=s.exists?s.data().subjectId||null:null}catch{}if(status)status.textContent='Authenticating…';const r=await upload(f,`college/${user().uid}/${subjectId||'general'}/${type}/${id}`,p=>{if(status)status.textContent=`Uploading ${p}%`});await saveFile('collegeFiles',{userId:user().uid,workspace:'college',subjectId,entityId:id,entityType:type,category:cat,name:f.name,size:f.size,contentType:f.type||'file',url:r.url,storageProvider:'imagekit',imagekitFileId:r.fileId,imagekitPath:r.filePath,imagekitVersionId:r.versionInfo?.id||null});await saveFile('college_activity',{userId:user().uid,action:'File uploaded',detail:f.name,entityId:id,entityType:type});if(status)status.textContent='Upload complete.';input.value='';setTimeout(()=>window.location.reload(),250)}catch(err){console.error(err);if(status)status.textContent=err.message||'Upload failed.'}finally{b.disabled=false}}
async function collegeDelete(e){const b=e.target.closest('[data-del-file]');if(!b)return;const id=b.dataset.delFile;if(!id)return;try{const snap=await firebase.firestore().collection('collegeFiles').doc(id).get();const f=snap.data();if(f?.storageProvider!=='imagekit'||!f.imagekitFileId)return;e.preventDefault();e.stopImmediatePropagation();if(!confirm('Delete this file from ImageKit and College storage?'))return;await deleteRemote(f.imagekitFileId);await firebase.firestore().collection('collegeFiles').doc(id).delete();await firebase.firestore().collection('college_activity').add({userId:user().uid,action:'File deleted',detail:f.name||id,entityId:f.entityId||null,entityType:f.entityType||null,createdAt:firebase.firestore.FieldValue.serverTimestamp()});b.closest('.cv3-file')?.remove()}catch(err){console.error(err);alert(err.message||'Unable to delete file.')}}
document.addEventListener('click',e=>{setContext(e);storageUpload(e);collegeUpload(e);collegeDelete(e)},true);
window.OVESH_IMAGEKIT={upload,deleteRemote};
})();
