(()=>{'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const files=()=>Array.isArray(window.OVESH_STORAGE?.files)?window.OVESH_STORAGE.files:[];
const getFile=k=>files().find(f=>String(f.objectKey||f.id)===String(k));
function toast(msg){const t=document.getElementById('toast');if(t){t.textContent=msg;t.classList.remove('hidden');clearTimeout(window.__ovShareToast);window.__ovShareToast=setTimeout(()=>t.classList.add('hidden'),3500)}else console.warn(msg)}
function styles(){if(document.getElementById('ovShareStyles'))return;const s=document.createElement('style');s.id='ovShareStyles';s.textContent='.b2-actions{display:flex!important;align-items:center!important;gap:6px!important;flex-wrap:wrap!important}.b2-share-button{display:inline-flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;justify-content:center!important;min-width:62px!important;height:34px!important;padding:0 11px!important;border:1px solid rgba(125,211,252,.42)!important;color:#dff5ff!important;background:rgba(125,211,252,.10)!important;border-radius:10px!important;cursor:pointer!important;font:inherit!important;font-size:12px!important;font-weight:700!important;position:relative!important;z-index:5!important}.b2-share-button:hover{background:rgba(125,211,252,.18)!important}.ov-share-modal{position:fixed;inset:0;z-index:100000;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(2,6,15,.78);backdrop-filter:blur(16px)}.ov-share-modal.open{display:flex}.ov-share-card{width:min(520px,96vw);border:1px solid rgba(255,255,255,.13);border-radius:22px;background:#0a1220;color:#eef4ff;box-shadow:0 35px 120px rgba(0,0,0,.6);overflow:hidden}.ov-share-head{display:flex;align-items:center;padding:16px 18px;border-bottom:1px solid rgba(255,255,255,.08)}.ov-share-head strong{flex:1}.ov-share-close{border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.06);color:inherit;border-radius:10px;width:36px;height:36px;font-size:20px;cursor:pointer}.ov-share-body{padding:20px}.ov-share-file{padding:13px;border:1px solid rgba(255,255,255,.09);border-radius:13px;background:rgba(255,255,255,.035);font-weight:700;word-break:break-word}.ov-share-url{display:flex;gap:8px;margin-top:14px}.ov-share-url input{flex:1;min-width:0;background:#050a13;border:1px solid rgba(255,255,255,.12);border-radius:11px;color:#dce8f8;padding:11px}.ov-share-copy{border:1px solid rgba(125,211,252,.3);background:rgba(125,211,252,.1);color:#dff5ff;border-radius:11px;padding:0 14px;font-weight:800;cursor:pointer}.ov-share-note{font-size:12px;opacity:.6;line-height:1.55;margin-top:12px}';document.head.appendChild(s)}
function modal(){styles();if(document.getElementById('ovShareModal'))return;const m=document.createElement('div');m.id='ovShareModal';m.className='ov-share-modal';m.innerHTML='<div class="ov-share-card"><div class="ov-share-head"><strong>Share from OVESH CLOUD™</strong><button class="ov-share-close" type="button">×</button></div><div class="ov-share-body"><div id="ovShareFile" class="ov-share-file"></div><div id="ovShareUrl" class="ov-share-url"></div><div class="ov-share-note">Only this selected file is exposed. Your private Cloud and other files stay protected.</div></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.ov-share-close'))m.classList.remove('open')})}
async function share(k){const f=getFile(k);if(!f){toast('This file is no longer available.');return}modal();const m=document.getElementById('ovShareModal');document.getElementById('ovShareFile').textContent=f.name||'Shared file';document.getElementById('ovShareUrl').innerHTML='<span style="opacity:.65;padding:10px 0">Generating secure link…</span>';m.classList.add('open');try{const r=await fetch('/api/oveshcloud-share-file',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'create',objectKey:k})});const x=await r.json();if(!r.ok||!x.ok)throw Error(x.error||'Unable to create share link.');document.getElementById('ovShareUrl').innerHTML='<input id="ovShareLinkInput" readonly><button class="ov-share-copy" type="button">COPY</button>';document.getElementById('ovShareLinkInput').value=x.shareUrl;document.querySelector('.ov-share-copy').onclick=async()=>{try{await navigator.clipboard.writeText(x.shareUrl)}catch{const i=document.getElementById('ovShareLinkInput');i.select();document.execCommand('copy')}toast('Share link copied.')}}catch(e){m.classList.remove('open');toast(e.message||'Unable to create share link.')}}
function makeButton(k){const b=document.createElement('button');b.type='button';b.className='b2-mini-btn b2-action b2-share-button';b.dataset.ovShare=k;b.textContent='Share';b.title='Create a secure link for this file';b.setAttribute('aria-label','Share this file');b.onclick=e=>{e.preventDefault();e.stopPropagation();share(k)};return b}
function inject(){styles();document.querySelectorAll('[data-b2-download]').forEach(d=>{const k=d.getAttribute('data-b2-download');if(!k)return;let wrap=d.closest('.b2-actions')||d.parentElement;if(!wrap)return;if(wrap.querySelector('[data-ov-share]'))return;wrap.insertBefore(makeButton(k),d)});document.querySelectorAll('.file-row:not(.head)').forEach(row=>{const d=row.querySelector('[data-b2-download]');if(!d)return;const wrap=row.querySelector('.b2-actions')||d.parentElement;if(!wrap||wrap.querySelector('[data-ov-share]'))return;wrap.insertBefore(makeButton(d.getAttribute('data-b2-download')),d)})}
function boot(){inject();[100,300,700,1200,2000,3500,5000].forEach(t=>setTimeout(inject,t));clearInterval(window.__ovShareInterval);window.__ovShareInterval=setInterval(inject,1000)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-ov-share]');if(b){e.preventDefault();e.stopPropagation();share(b.dataset.ovShare)}},true);
new MutationObserver(()=>inject()).observe(document.body,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.addEventListener('ovesh:b2-files',inject);
window.OVESH_SHARE={share,inject};
})();

// Login safety guard: the legacy Security Logs overlay must never block entry.
(()=>{'use strict';
const continueToWorkspace=()=>{const b=document.getElementById('continueBtn');if(b){b.click();return true}return false};
const enterWorkspace=()=>{const w=document.getElementById('welcomeView'),b=document.getElementById('enterBtn');if(w&&!w.classList.contains('hidden')&&b){b.click();return true}return false};
const guard=()=>{const s=document.getElementById('securityView');if(s&&!s.classList.contains('hidden')){continueToWorkspace();setTimeout(enterWorkspace,80);setTimeout(enterWorkspace,250);setTimeout(enterWorkspace,700)}};
new MutationObserver(guard).observe(document.documentElement,{subtree:true,attributes:true,attributeFilter:['class']});
setInterval(guard,250);
})();
