(()=>{'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const files=()=>Array.isArray(window.OVESH_STORAGE?.files)?window.OVESH_STORAGE.files:[];
const getFile=k=>files().find(f=>String(f.objectKey||f.id)===String(k));
function toast(msg){const t=document.getElementById('toast');if(t){t.textContent=msg;t.classList.remove('hidden');clearTimeout(window.__ovShareToast);window.__ovShareToast=setTimeout(()=>t.classList.add('hidden'),3500)}else alert(msg)}
function styles(){if(document.getElementById('ovShareStyles'))return;const s=document.createElement('style');s.id='ovShareStyles';s.textContent='.ov-share-modal{position:fixed;inset:0;z-index:100000;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(2,6,15,.78);backdrop-filter:blur(16px)}.ov-share-modal.open{display:flex}.ov-share-card{width:min(520px,96vw);border:1px solid rgba(255,255,255,.13);border-radius:22px;background:#0a1220;color:#eef4ff;box-shadow:0 35px 120px rgba(0,0,0,.6);overflow:hidden}.ov-share-head{display:flex;align-items:center;padding:16px 18px;border-bottom:1px solid rgba(255,255,255,.08)}.ov-share-head strong{flex:1}.ov-share-close{border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.06);color:inherit;border-radius:10px;width:36px;height:36px;font-size:20px;cursor:pointer}.ov-share-body{padding:20px}.ov-share-file{padding:13px;border:1px solid rgba(255,255,255,.09);border-radius:13px;background:rgba(255,255,255,.035);font-weight:700;word-break:break-word}.ov-share-url{display:flex;gap:8px;margin-top:14px}.ov-share-url input{flex:1;min-width:0;background:#050a13;border:1px solid rgba(255,255,255,.12);border-radius:11px;color:#dce8f8;padding:11px}.ov-share-copy{border:1px solid rgba(125,211,252,.3);background:rgba(125,211,252,.1);color:#dff5ff;border-radius:11px;padding:0 14px;font-weight:800;cursor:pointer}.ov-share-note{font-size:12px;opacity:.6;line-height:1.55;margin-top:12px}.b2-share-button{display:inline-flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;justify-content:center!important;min-width:58px!important;border:1px solid rgba(125,211,252,.35)!important;color:#dff5ff!important;background:rgba(125,211,252,.08)!important;cursor:pointer!important}';document.head.appendChild(s)}
function modal(){styles();if(document.getElementById('ovShareModal'))return;const m=document.createElement('div');m.id='ovShareModal';m.className='ov-share-modal';m.innerHTML='<div class="ov-share-card"><div class="ov-share-head"><strong>Share from OVESH CLOUD™</strong><button class="ov-share-close" type="button">×</button></div><div class="ov-share-body"><div id="ovShareFile" class="ov-share-file"></div><div id="ovShareUrl" class="ov-share-url"></div><div class="ov-share-note">Only this selected file is exposed. Your private Cloud and other files stay protected.</div></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.ov-share-close'))m.classList.remove('open')})}
async function share(k){const f=getFile(k);if(!f){toast('This file is no longer available.');return}modal();const m=document.getElementById('ovShareModal');document.getElementById('ovShareFile').textContent=f.name||'Shared file';document.getElementById('ovShareUrl').innerHTML='<span style="opacity:.65;padding:10px 0">Generating secure link…</span>';m.classList.add('open');try{const r=await fetch('/api/oveshcloud-share-file',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'create',objectKey:k})});const x=await r.json();if(!r.ok||!x.ok)throw Error(x.error||'Unable to create share link.');document.getElementById('ovShareUrl').innerHTML='<input id="ovShareLinkInput" readonly><button class="ov-share-copy" type="button">COPY</button>';document.getElementById('ovShareLinkInput').value=x.shareUrl;document.querySelector('.ov-share-copy').onclick=async()=>{try{await navigator.clipboard.writeText(x.shareUrl)}catch{const i=document.getElementById('ovShareLinkInput');i.select();document.execCommand('copy')}toast('Share link copied.')}}catch(e){m.classList.remove('open');toast(e.message||'Unable to create share link.')}}
function inject(){document.querySelectorAll('.file-row:not(.head)').forEach(row=>{const d=row.querySelector('[data-b2-download]');if(!d)return;let wrap=row.querySelector('.b2-actions');if(!wrap){wrap=document.createElement('span');wrap.className='b2-actions';row.appendChild(wrap)}if(wrap.querySelector('[data-ov-share]'))return;const b=document.createElement('button');b.type='button';b.className='b2-mini-btn b2-action b2-share-button';b.dataset.ovShare=d.getAttribute('data-b2-download');b.textContent='Share';b.title='Share this file';b.onclick=e=>{e.preventDefault();e.stopPropagation();share(b.dataset.ovShare)};wrap.insertBefore(b,wrap.firstChild)})}
function boot(){inject();setTimeout(inject,100);setTimeout(inject,500);setTimeout(inject,1200);setTimeout(inject,2500);setInterval(inject,1500)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-ov-share]');if(b){e.preventDefault();e.stopPropagation();share(b.dataset.ovShare)}},true);
new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.addEventListener('ovesh:b2-files',inject);
})();