(()=>{'use strict';
const escSO=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let shopOrders=[],shopFilter='all',shopSearch='';
const money=v=>v===null||v===undefined||v===''?'—':'₹'+Number(v||0).toLocaleString('en-IN');
const date=v=>{if(!v)return'—';try{return new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}catch{return'—'}};
const services=o=>o.items?.length?o.items.map(x=>x.name).join(', '):o.selectedService||'Custom service';
const st=o=>String(o.status||'Pending'), pay=o=>String(o.paymentStatus||'Quote / payment pending');
const agr=o=>o.signature?.signedAt?'SIGNED':o.agreementAccepted?'ACCEPTED':'PENDING';
async function loadShopOrders(){
 const p=document.querySelector('#page');if(!p)return;p.innerHTML='<div class="so-loading"><div class="so-spinner"></div><h3>Loading Shop Orders</h3><p>Securely retrieving your private Cyber Labs orders…</p></div>';
 try{const r=await fetch('/api/oveshcloud-auth?action=shop-orders',{credentials:'same-origin'}),x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.error||'Unable to load Shop Orders');shopOrders=x.orders||[];renderShopOrders()}catch(e){p.innerHTML='<div class="so-error"><strong>Shop Orders unavailable</strong><p>'+escSO(e.message)+'</p><button class="primary-btn" id="soRetry">TRY AGAIN</button></div>';document.querySelector('#soRetry')?.addEventListener('click',loadShopOrders)}
}
function renderShopOrders(){
 const f=shopOrders.filter(o=>{const q=shopSearch.toLowerCase(),ok=!q||[o.orderId,o.fullName,o.email,o.phone,o.selectedService,services(o)].join(' ').toLowerCase().includes(q);if(!ok)return false;if(shopFilter==='pending')return /pending|review|new/i.test(st(o));if(shopFilter==='progress')return /progress|active|development/i.test(st(o));if(shopFilter==='completed')return /completed|delivered|closed/i.test(st(o));if(shopFilter==='agreement')return agr(o)==='SIGNED';return true});
 const pending=shopOrders.filter(o=>/pending|review|new/i.test(st(o))).length,progress=shopOrders.filter(o=>/progress|active|development/i.test(st(o))).length,completed=shopOrders.filter(o=>/completed|delivered|closed/i.test(st(o))).length,signed=shopOrders.filter(o=>agr(o)==='SIGNED').length;
 document.querySelector('#page').innerHTML=`<div class="so-shell"><div class="so-hero"><div><div class="hero-tag">OVESH MALPURA CYBER LABS · PRIVATE OPERATIONS</div><h1>Shop Orders</h1><p>Central order management for service requests submitted through the Cyber Labs Shop. Private to your OVESH CLOUD owner session.</p></div><button class="so-refresh" id="soRefresh">↻ Refresh</button></div>
 <div class="so-stats"><button class="so-stat active" data-so-filter="all"><small>ALL ORDERS</small><strong>${shopOrders.length}</strong><span>Shop requests</span></button><button class="so-stat" data-so-filter="pending"><small>PENDING</small><strong>${pending}</strong><span>Need attention</span></button><button class="so-stat" data-so-filter="progress"><small>IN PROGRESS</small><strong>${progress}</strong><span>Active work</span></button><button class="so-stat" data-so-filter="completed"><small>COMPLETED</small><strong>${completed}</strong><span>Delivered work</span></button><button class="so-stat" data-so-filter="agreement"><small>SIGNATURES</small><strong>${signed}</strong><span>Signed agreements</span></button></div>
 <div class="so-toolbar"><div class="so-search">⌕ <input id="soSearch" placeholder="Search order ID, client, email or service…" value="${escSO(shopSearch)}"></div><span>SHOWING <b>${f.length}</b> / ${shopOrders.length}</span></div><div class="so-list">${f.length?f.map(orderCard).join(''):'<div class="so-empty"><strong>No matching orders</strong><span>Try another search or filter.</span></div>'}</div></div>`;
 document.querySelectorAll('[data-so-filter]').forEach(b=>b.onclick=()=>{shopFilter=b.dataset.soFilter;renderShopOrders()});
 document.querySelector('#soSearch').oninput=e=>{shopSearch=e.target.value;renderShopOrders();const q=document.querySelector('#soSearch');q.focus();q.setSelectionRange(q.value.length,q.value.length)};
 document.querySelector('#soRefresh').onclick=loadShopOrders;document.querySelectorAll('[data-so-open]').forEach(b=>b.onclick=()=>openOrder(b.dataset.soOpen));
}
function orderCard(o){return`<article class="so-order"><div class="so-order-head"><div><span class="so-order-id">${escSO(o.orderId)}</span><h3>${escSO(o.fullName)}</h3><p>${escSO(services(o))}</p></div><div class="so-badges"><span>${escSO(st(o))}</span><span class="${agr(o)==='SIGNED'?'signed':''}">${agr(o)==='SIGNED'?'✓ Signed':o.agreementAccepted?'✓ Accepted':'Agreement pending'}</span></div></div><div class="so-order-grid"><div><small>CONTACT</small><b>${escSO(o.email)}</b><span>${escSO(o.phone)}</span></div><div><small>ESTIMATED TOTAL</small><b>${money(o.estimatedTotal)}</b><span>${escSO(pay(o))}</span></div><div><small>REQUESTED</small><b>${date(o.createdAt)}</b><span>${escSO(o.orderId)}</span></div><div><small>AGREEMENT</small><b>${escSO(o.agreementVersion||'—')}</b><span>${o.signature?escSO(o.signature.signatureType||'Electronic signature'):'Signature pending'}</span></div></div><div class="so-order-foot"><span>${o.items?.length||1} service${(o.items?.length||1)===1?'':'s'} · ${o.projectDescription?'Project brief provided':'No project brief'}</span><button data-so-open="${escSO(o.orderId)}">VIEW ORDER DETAILS →</button></div></article>`}
function openOrder(id){const o=shopOrders.find(x=>x.orderId===id);if(!o)return;document.querySelector('#page').innerHTML=`<div class="so-detail"><button class="so-back" id="soBack">← SHOP ORDERS</button><div class="so-detail-hero"><div><div class="hero-tag">SERVICE REQUEST · PRIVATE</div><h1>${escSO(o.orderId)}</h1><p>${escSO(o.fullName)} · ${escSO(o.email)}</p></div><span class="so-detail-status">${escSO(st(o))}</span></div><div class="so-detail-grid"><section class="so-panel"><header><h3>Client Information</h3><span>REQUESTER</span></header><dl><dt>Full name</dt><dd>${escSO(o.fullName)}</dd><dt>Email</dt><dd>${escSO(o.email)}</dd><dt>Phone</dt><dd>${escSO(o.phone)}</dd></dl></section><section class="so-panel"><header><h3>Order Summary</h3><span>SHOP</span></header><dl><dt>Services</dt><dd>${escSO(services(o))}</dd><dt>Estimated total</dt><dd>${money(o.estimatedTotal)}</dd><dt>Payment</dt><dd>${escSO(pay(o))}</dd><dt>Requested</dt><dd>${date(o.createdAt)}</dd></dl></section></div><section class="so-panel"><header><h3>Selected Services</h3><span>${o.items?.length||0} ITEMS</span></header><div class="so-services">${o.items?.length?o.items.map(i=>`<div><b>${escSO(i.name)}</b><span>Qty ${Number(i.quantity||1)} · ${money(i.price)}</span></div>`).join(''):`<div><b>${escSO(o.selectedService)}</b><span>Custom request</span></div>`}</div></section><section class="so-panel"><header><h3>Project Description</h3><span>CLIENT BRIEF</span></header><p class="so-description">${escSO(o.projectDescription||'No project description was provided.')}</p></section><div class="so-detail-grid"><section class="so-panel"><header><h3>Agreement</h3><span>${escSO(o.agreementVersion||'—')}</span></header><div class="so-checkline"><b>${o.agreementAccepted?'✓ Agreement accepted':'○ Agreement not accepted'}</b><span>${date(o.agreementAcceptedAt)}</span></div><div class="so-checkline"><b>${o.signature?'✓ Electronically signed':'○ Signature pending'}</b><span>${o.signature?escSO(o.signature.fullName||'Signed client'):'Not signed'}</span></div></section><section class="so-panel"><header><h3>Order Timeline</h3><span>RECORD</span></header><div class="so-timeline"><div><i></i><b>Request created</b><span>${date(o.createdAt)}</span></div>${o.agreementAcceptedAt?`<div><i></i><b>Agreement acknowledged</b><span>${date(o.agreementAcceptedAt)}</span></div>`:''}${o.signature?.signedAt?`<div><i></i><b>Agreement signed</b><span>${date(o.signature.signedAt)}</span></div>`:''}</div></section></div></div>`;document.querySelector('#soBack').onclick=renderShopOrders}
window.addEventListener('DOMContentLoaded',()=>{const b=document.querySelector('#nav [data-page="shop-orders"]');if(!b)return;b.onclick=e=>{e.preventDefault();document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#pageTitle').textContent='Shop Orders';loadShopOrders()}});
})();